#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

extra-y	= start.o

obj-$(CONFIG_CPU_PXA25X)	+= pxa2xx.o
obj-$(CONFIG_CPU_PXA27X)	+= pxa2xx.o

obj-y	+= cpuinfo.o
obj-y	+= timer.o
obj-y	+= usb.o
obj-y	+= relocate.o
