#
# SPDX-License-Identifier:	GPL-2.0+
#

head-$(CONFIG_CPU_MIPS32) := arch/mips/cpu/mips32/start.o
head-$(CONFIG_CPU_MIPS64) := arch/mips/cpu/mips64/start.o

libs-$(CONFIG_CPU_MIPS32) += arch/mips/cpu/mips32/
libs-$(CONFIG_CPU_MIPS64) += arch/mips/cpu/mips64/
libs-y += arch/mips/lib/

libs-$(CONFIG_SOC_AU1X00) += arch/mips/mach-au1x00/
