# Copyright 2017 General Electric Company
#
# Based on board/freescale/mx53loco/Makefile:
#
# (C) Copyright 2011 Freescale Semiconductor, Inc.
# Jason Liu <r64343@freescale.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y			+= mx53ppd.o
obj-$(CONFIG_VIDEO)	+= mx53ppd_video.o
