#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y					+= boot-mode.o

obj-$(CONFIG_ARCH_UNIPHIER_SLD3)	+= boot-mode-sld3.o
obj-$(CONFIG_ARCH_UNIPHIER_LD4)		+= boot-mode-ld4.o
obj-$(CONFIG_ARCH_UNIPHIER_PRO4)	+= boot-mode-ld4.o
obj-$(CONFIG_ARCH_UNIPHIER_SLD8)	+= boot-mode-ld4.o
obj-$(CONFIG_ARCH_UNIPHIER_PRO5)	+= boot-mode-pro5.o
obj-$(CONFIG_ARCH_UNIPHIER_PXS2)	+= boot-mode-pxs2.o
obj-$(CONFIG_ARCH_UNIPHIER_LD6B)	+= boot-mode-pxs2.o
obj-$(CONFIG_ARCH_UNIPHIER_LD20)	+= boot-mode-ld20.o

obj-$(CONFIG_CMD_PINMON) += cmd_pinmon.o
