#
#  (C) Copyright 2012 Lucas Stach
#
# SPDX-License-Identifier:	GPL-2.0+
#

$(shell mkdir -p $(obj)../../nvidia/common)
$(shell mkdir -p $(obj)../colibri_t20-common)

obj-y	:= ../../nvidia/common/board.o
obj-y	+= ../colibri_t20-common/colibri_t20-common.o
obj-y	+= colibri_t20_iris.o
