# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2010-2020 CS Group
# Charles Frey <charles.frey@c-s.fr>
# Christophe Leroy <christophe.leroy@c-s.fr>
#

obj-y += cmpc885.o ../common/common.o
obj-y += sdram.o
obj-$(CONFIG_CMD_NAND) += nand.o
