# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2025 Junhui Liu <junhui.liu@pigmoral.tech>

obj-$(CONFIG_CLK_SPACEMIT) += clk_ddn.o clk_mix.o clk_pll.o

obj-$(CONFIG_CLK_SPACEMIT_K1)	+= clk-k1.o
