# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2020 Amarula Solutions(India)
#

obj-$(CONFIG_PHY_ROCKCHIP_INNO_USB2)	+= phy-rockchip-inno-usb2.o
obj-$(CONFIG_PHY_ROCKCHIP_TYPEC)	+= phy-rockchip-typec.o
