#
# (C) Copyright 2008
# Ricardo Ribalda,Universidad Autonoma de Madrid, ricardo.ribalda@uam.es
# This work has been supported by: Qtechnology http://qtec.com/
#
# SPDX-License-Identifier:	GPL-2.0+
#

COBJS	+= $(BOARD).o

include $(SRCTREE)/board/xilinx/ppc405-generic/Makefile
