# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2016 Nexell
# Junghyun, kim<jhkim@nexell.co.kr>

obj-$(CONFIG_VIDEO_NX) += s5pxx18_soc_dpc.o s5pxx18_soc_mlc.o \
			  s5pxx18_soc_disptop.o s5pxx18_soc_disptop_clk.o

obj-$(CONFIG_VIDEO_NX_LVDS) += s5pxx18_soc_lvds.o
obj-$(CONFIG_VIDEO_NX_MIPI) += s5pxx18_soc_mipi.o
obj-$(CONFIG_VIDEO_NX_HDMI) += s5pxx18_soc_hdmi.o
