#
# (C) Copyright 2008 Dmitry Rakhchev, EmCraft Systems, rda@emcraft.com
#
# Developed for DENX Software Engineering GmbH
#
# SPDX-License-Identifier:	GPL-2.0+

obj-y += sysmon.o watchdog.o dspic.o fpga.o dsp.o gdc.o
