# SPDX-License-Identifier: GPL-2.0+
#
# Copyright 2023 Arm Limited and/or its affiliates <open-source-office@arm.com>
# Authors:
#   Abdellatif El Khlifi <abdellatif.elkhlifi@arm.com>

obj-y += nvmxip-uclass.o nvmxip.o
obj-$(CONFIG_NVMXIP_QSPI) += nvmxip_qspi.o
