# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2021 - 2022, Xilinx, Inc.
# Copyright (C) 2022, Advanced Micro Devices, Inc.
#
# Michal Simek <michal.simek@amd.com>
#

obj-y	:= board.o
obj-$(CONFIG_CMD_VERSAL_NET)	+= cmds.o
