#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2003
# Martin Winistoerfer, martinwinistoerfer@gmx.ch.
#
# SPDX-License-Identifier:	GPL-2.0+
#

#
# File:			arch/powerpc/cpu/mpc5xx/Makefile
#
# Discription:		Makefile to build mpc5xx cpu configuration.
#			Will include top config.mk which itselfs
#			uses the definitions made in arch/powerpc/cpu/mpc5xx/config.mk
#

extra-y	= start.o
obj-y	= serial.o cpu.o cpu_init.o interrupts.o traps.o speed.o spi.o
