# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2022 Google, Inc.
# Written by Andrew Scull <ascull@google.com>
#

obj-$(CONFIG_$(PHASE_)CMDLINE) += cmd_fuzz.o
obj-$(CONFIG_VIRTIO_SANDBOX) += virtio.o
