# SPDX-License-Identifier: GPL-2.0+ OR BSD-3-Clause
#
# Copyright (C) 2018, STMicroelectronics - All Rights Reserved
#

obj-y += cpu.o
obj-y += dram_init.o
obj-y += syscon.o

obj-$(CONFIG_SPL_BUILD) += spl.o
