# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2021 Dzmitry Sankouski <dsankouski@gmail.com>
#
# This empty file prevents make error.
# Board logic defined in board/qualcomm/common/sdm845.c, no custom logic for starqltechn so far.
#

obj-y += starqltechn.o
