# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2023 Texas Instruments Incorporated - https://www.ti.com/
# Nikhil M Jain, n-jain1@ti.com
#
# based on the linux tidss driver, which is
#
# (C) Copyright 2018 Texas Instruments Incorporated - https://www.ti.com/
# Author: Tomi Valkeinen <tomi.valkeinen@ti.com>


obj-${CONFIG_$(PHASE_)VIDEO_TIDSS} = tidss_drv.o
