# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_HOST1X_TEGRA) += host1x.o
obj-$(CONFIG_VIDEO_TEGRA) += dc.o
obj-$(CONFIG_VIDEO_DSI_TEGRA) += dsi.o mipi.o mipi-phy.o
obj-$(CONFIG_VIDEO_HDMI_TEGRA) += hdmi.o
obj-$(CONFIG_TEGRA_BACKLIGHT_PWM) += dc-pwm-backlight.o
obj-$(CONFIG_TEGRA_8BIT_CPU_BRIDGE) += cpu-bridge.o

obj-${CONFIG_VIDEO_TEGRA124} += tegra124/
