#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	= elppc.o flash.o pci.o misc.o mpc107_i2c.o eepro100_srom.o
obj-y	+= asm_init.o
