#
# Author: Masami Hiramatsu <masami.hiramatsu@linaro.org>
#
# Copyright (C) 2021 Linaro Ltd.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= developerbox.o
obj-$(CONFIG_FWU_MDATA_MTD) += fwu_plat.o
