# SPDX-License-Identifier: GPL-2.0+
######################################################################### Copyright (C) 2008 Renesas Solutions Corp.
# Copyright (C) 2008 Nobuhiro Iwamatsu <iwamatsu.nobuhiro@renesas.com>
#
# board/ap325rxa/Makefile
#
#

obj-y	:= ap325rxa.o cpld-ap325rxa.o
extra-y	+= lowlevel_init.o
