#
# (C) Copyright 2007
# Stefan Roese, DENX Software Engineering, sr@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y := 405ep.o
obj-$(CONFIG_NEO) += neo.o
obj-$(CONFIG_IO) += io.o
obj-$(CONFIG_IOCON) += iocon.o
obj-$(CONFIG_DLVISION_10G) += dlvision-10g.o
