# SPDX-License-Identifier: GPL-2.0+
#
#  (C) Copyright 2010-2012
#  NVIDIA Corporation <www.nvidia.com>
#
#  (C) Copyright 2021
#  Svyatoslav Ryhel <clamor95@gmail.com>

obj-$(CONFIG_XPL_BUILD) += grouper-spl.o
obj-$(CONFIG_MULTI_DTB_FIT) += board-info.o

obj-y += grouper.o
