# SPDX-License-Identifier: GPL-2.0+
#
#  (C) Copyright 2010-2012
#  NVIDIA Corporation <www.nvidia.com>
#
#  (C) Copyright 2021
#  Svyatoslav Ryhel <clamor95@gmail.com>

ifdef CONFIG_SPL_BUILD
obj-$(CONFIG_GROUPER_MAX77663) += grouper-spl-max.o
obj-$(CONFIG_GROUPER_TPS65911) += grouper-spl-ti.o
endif

obj-y += grouper.o
