#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_ARCH_UNIPHIER_SLD3)	+= clk-ld4.o
obj-$(CONFIG_ARCH_UNIPHIER_LD4)		+= clk-ld4.o
obj-$(CONFIG_ARCH_UNIPHIER_PRO4)	+= clk-pro4.o
obj-$(CONFIG_ARCH_UNIPHIER_SLD8)	+= clk-ld4.o
obj-$(CONFIG_ARCH_UNIPHIER_PRO5)	+= clk-pro5.o
obj-$(CONFIG_ARCH_UNIPHIER_PXS2)	+= clk-pxs2.o
obj-$(CONFIG_ARCH_UNIPHIER_LD6B)	+= clk-pxs2.o
obj-$(CONFIG_ARCH_UNIPHIER_LD11)	+= clk-ld11.o
obj-$(CONFIG_ARCH_UNIPHIER_LD20)	+= clk-ld20.o
