# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2023, Phytium Technology Co., Ltd.
# lixinde		<lixinde@phytium.com.cn>
# weichangzheng	<weichangzheng@phytium.com.cn>
#

obj-y	+= pe2201.o
obj-y	+= pll.o
obj-y	+= pcie.o
obj-y	+= ddr.o
obj-y	+= sec.o
