# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2024 Linaro Ltd.

ccflags-y += -I$(srctree)/lib/lwip/include -I$(srctree)/lib/lwip/u-boot

obj-y += \
	api/api_lib.o \
	api/api_msg.o \
	api/err.o \
	api/if_api.o \
	api/netbuf.o \
	api/netdb.o \
	api/netifapi.o \
	api/sockets.o \
	api/tcpip.o \
	apps/http/http_client.o \
	apps/tftp/tftp.o \
	core/altcp_alloc.o \
	core/altcp.o \
	core/altcp_tcp.o \
	core/def.o \
	core/dns.o \
	core/inet_chksum.o \
	core/init.o \
	core/ip.o \
	core/ipv4/acd.o \
	core/ipv4/autoip.o \
	core/ipv4/dhcp.o \
	core/ipv4/etharp.o \
	core/ipv4/icmp.o \
	core/ipv4/igmp.o \
	core/ipv4/ip4_addr.o \
	core/ipv4/ip4.o \
	core/ipv4/ip4_frag.o \
	core/ipv6/dhcp6.o \
	core/ipv6/ethip6.o \
	core/ipv6/icmp6.o \
	core/ipv6/inet6.o \
	core/ipv6/ip6_addr.o \
	core/ipv6/ip6.o \
	core/ipv6/ip6_frag.o \
	core/ipv6/mld6.o \
	core/ipv6/nd6.o \
	core/mem.o \
	core/memp.o \
	core/netif.o \
	core/pbuf.o \
	core/raw.o \
	core/stats.o \
	core/sys.o \
	core/tcp.o \
	core/tcp_in.o \
	core/tcp_out.o \
	core/timeouts.o \
	core/udp.o \
	netif/ethernet.o
