#
# (C) Copyright 2000, 2001, 2002
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# Copyright (C) 2007 Sergey Kubushyn <ksi@koi8.net>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_MACH_DAVINCI_DA830_EVM)	+= da830evm.o
obj-$(CONFIG_MACH_DAVINCI_DA850_EVM)	+= da850evm.o
obj-$(CONFIG_MACH_DAVINCI_HAWK)		+= hawkboard.o
