# SPDX-License-Identifier: GPL-2.0+
# (C) 2022 Pali Rohár <pali@kernel.org>

ifdef CONFIG_SPL_BUILD
obj-y	+= ../../freescale/p1_p2_rdb_pc/spl.o
endif

obj-y	+= ../../freescale/p1_p2_rdb_pc/p1_p2_rdb_pc.o
obj-y	+= ../turris_atsha_otp.o
obj-y	+= ../turris_common.o

obj-y	+= turris_1x.o
obj-y	+= ddr.o
obj-y	+= law.o
obj-y	+= tlb.o
