# SPDX-License-Identifier: GPL-2.0+
# Copyright 2026 Free Mobile - Vincent Jardin
#

obj-y += eth_nbxv3.o
obj-y += mps_pmbus.o
obj-y += psu_pmbus.o
obj-y += vid_handoff.o
obj-y += carrier.o
obj-y += dpll_zl30733.o
obj-y += fan_power.o
