# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2021
# lixinde         <lixinde@phytium.com.cn>
# weichangzheng   <weichangzheng@phytium.com.cn>
#

obj-y += pomelo.o
obj-y += pll.o
obj-y += pcie.o
obj-y += ddr.o
obj-y += sec.o


