# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2016 Samsung Electronics
# Thomas Abraham <thomas.ab@samsung.com>

obj-$(CONFIG_PINCTRL_EXYNOS)		+= pinctrl-exynos.o
obj-$(CONFIG_PINCTRL_EXYNOS7420)	+= pinctrl-exynos7420.o
obj-$(CONFIG_PINCTRL_EXYNOS78x0)	+= pinctrl-exynos78x0.o
