#
# Copyright (C) 2016 Samsung Electronics
# Thomas Abraham <thomas.ab@samsung.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_PINCTRL_EXYNOS)		+= pinctrl-exynos.o
obj-$(CONFIG_PINCTRL_EXYNOS7420)	+= pinctrl-exynos7420.o
