#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	= pip405.o cmd_pip405.o \
		../common/pci.o \
		../common/isa.o \
		../common/kbd.o \
		../common/usb_uhci.o \
		../common/common_util.o
obj-y	+= init.o
