#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

# ccflags-y += -DET_DEBUG

extra-y += start.o
extra-y += traps.o
obj-y	+= bedbug_860.o
obj-y	+= commproc.o
obj-y	+= cpu.o
obj-y	+= cpu_init.o
obj-y	+= fec.o
obj-$(CONFIG_OF_LIBFDT) += fdt.o
obj-y	+= i2c.o
obj-y	+= interrupts.o
obj-y	+= scc.o
obj-y	+= serial.o
obj-y	+= speed.o
obj-y	+= spi.o
obj-y	+= upatch.o
obj-y	+= video.o
obj-y	+= kgdb.o
obj-y	+= plprcr_write.o
