#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2002
# Stäubli Faverges - <www.staubli.com>
# Pierre AUBERT  p.aubert@staubli.com
#
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y := fat.o vfat.o dev.o fdos.o fs.o subdir.o
