# SPDX-License-Identifier: GPL-2.0+

obj-y					+= pinctrl-meson.o
obj-$(CONFIG_PINCTRL_MESON_GX_PMX)	+= pinctrl-meson-gx-pmx.o
obj-$(CONFIG_PINCTRL_MESON_GXBB)	+= pinctrl-meson-gxbb.o
obj-$(CONFIG_PINCTRL_MESON_GXL)		+= pinctrl-meson-gxl.o
