#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2008-2009 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= generic.o
obj-y	+= timer.o
obj-y	+= mx35_sdram.o
obj-y	+= relocate.o
