#
# (C) Copyright 2000-2012
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

ifndef	CONFIG_SPL_BUILD
obj-y	:= sc_sps_1.o
else
obj-y	:= spl_boot.o
endif
