CC = ppc-elf32-gcc
AR = ppc-elf32-ar

CFLAGS = -D__DRIVER__ -I../../include -DDEBUG -I.

BIOS_OBJS = biosemu.o bios.o besys.o
X86_OBJS = sys.o decode.o ops.o prim_ops.o fpu.o debug.o

libbios.a: $(BIOS_OBJS)
	$(AR) rcs libbios.a $(BIOS_OBJS)