#
# Makefile
#
# Copyright (C) 2014 Hannes Schmelzer <oe5hpm@oevsv.at> -
# Bernecker & Rainer Industrielektronik GmbH - http://www.br-automation.com/
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_SPL_BUILD) += mux.o
obj-y	+= ../common/common.o
obj-y	+= board.o
