# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2016 Nexell
# Hyunseok, Jung <hsjung@nexell.co.kr>

obj-y				+= clock.o
obj-y				+= timer.o
obj-y				+= reset.o
obj-y				+= nx_gpio.o
obj-y				+= tieoff.o
obj-$(CONFIG_ARCH_S5P4418)	+= reg-call.o
obj-$(CONFIG_ARCH_S5P4418)	+= nx_sec_reg.o
obj-$(CONFIG_CMD_BOOTL)		+= cmd_boot_linux.o
