# SPDX-License-Identifier: GPL-2.0+
#
# Copyright 2013 Broadcom Corporation.

obj-y	+= reset.o
obj-y	+= clk-core.o
obj-y	+= clk-bcm281xx.o
obj-y	+= clk-sdio.o
obj-y	+= clk-bsc.o
obj-y	+= clk-usb-otg.o
