# SPDX-License-Identifier: GPL-2.0+
#
# Makefile
#
# Copyright (C) 2013 Texas Instruments Incorporated - https://www.ti.com/

ifeq ($(CONFIG_$(PHASE_)SKIP_LOWLEVEL_INIT),)
obj-y	:= mux.o
endif

obj-y	+= board.o
