// SPDX-License-Identifier: GPL-2.0+
/*
 * NEORV32 SYSINFO definitions
 */

#ifndef __NEORV32_SYSINFO_H
#define __NEORV32_SYSINFO_H

#include <linux/types.h>
#include <asm/io.h>

#include <neorv32/neorv32.h>

/* SYSINFO register offsets */
#define NEORV32_SYSINFO_CLK   0x00
#define NEORV32_SYSINFO_MISC  0x04
#define NEORV32_SYSINFO_SOC   0x08
#define NEORV32_SYSINFO_CACHE 0x0c

/* SYSINFO.MISC fields */
enum NEORV32_SYSINFO_MISC_enum {
	SYSINFO_MISC_IMEM_LSB =  0,
	SYSINFO_MISC_IMEM_MSB =  7,
	SYSINFO_MISC_DMEM_LSB =  8,
	SYSINFO_MISC_DMEM_MSB = 15,
	SYSINFO_MISC_HART_LSB = 16,
	SYSINFO_MISC_HART_MSB = 19,
	SYSINFO_MISC_BOOT_LSB = 20,
	SYSINFO_MISC_BOOT_MSB = 21,
	SYSINFO_MISC_ITMO_LSB = 22,
	SYSINFO_MISC_ITMO_MSB = 26,
	SYSINFO_MISC_ETMO_LSB = 27,
	SYSINFO_MISC_ETMO_MSB = 31,
};

/* SYSINFO.SOC fields */
enum NEORV32_SYSINFO_SOC_enum {
	SYSINFO_SOC_BOOTLOADER =  0,
	SYSINFO_SOC_XBUS       =  1,
	SYSINFO_SOC_IMEM       =  2,
	SYSINFO_SOC_DMEM       =  3,
	SYSINFO_SOC_OCD        =  4,
	SYSINFO_SOC_ICACHE     =  5,
	SYSINFO_SOC_DCACHE     =  6,
	SYSINFO_SOC_OCD_AUTH   = 11,
	SYSINFO_SOC_IMEM_ROM   = 12,
	SYSINFO_SOC_IO_TWD     = 13,
	SYSINFO_SOC_IO_DMA     = 14,
	SYSINFO_SOC_IO_GPIO    = 15,
	SYSINFO_SOC_IO_CLINT   = 16,
	SYSINFO_SOC_IO_UART0   = 17,
	SYSINFO_SOC_IO_SPI     = 18,
	SYSINFO_SOC_IO_TWI     = 19,
	SYSINFO_SOC_IO_PWM     = 20,
	SYSINFO_SOC_IO_WDT     = 21,
	SYSINFO_SOC_IO_CFS     = 22,
	SYSINFO_SOC_IO_TRNG    = 23,
	SYSINFO_SOC_IO_SDI     = 24,
	SYSINFO_SOC_IO_UART1   = 25,
	SYSINFO_SOC_IO_NEOLED  = 26,
	SYSINFO_SOC_IO_TRACER  = 27,
	SYSINFO_SOC_IO_GPTMR   = 28,
	SYSINFO_SOC_IO_SLINK   = 29,
	SYSINFO_SOC_IO_ONEWIRE = 30,
};

/* SYSINFO.CACHE fields */
enum NEORV32_SYSINFO_CACHE_enum {
	SYSINFO_CACHE_INST_BLOCK_SIZE_0 =  0,
	SYSINFO_CACHE_INST_BLOCK_SIZE_3 =  3,
	SYSINFO_CACHE_INST_NUM_BLOCKS_0 =  4,
	SYSINFO_CACHE_INST_NUM_BLOCKS_3 =  7,
	SYSINFO_CACHE_DATA_BLOCK_SIZE_0 =  8,
	SYSINFO_CACHE_DATA_BLOCK_SIZE_3 = 11,
	SYSINFO_CACHE_DATA_NUM_BLOCKS_0 = 12,
	SYSINFO_CACHE_DATA_NUM_BLOCKS_3 = 15,
	SYSINFO_CACHE_INST_BURSTS_EN    = 16,
	SYSINFO_CACHE_DATA_BURSTS_EN    = 24,
};

static inline u32 neorv32_sysinfo_get_clk(void)
{
	return readl((void __iomem *)(uintptr_t)(NEORV32_SYSINFO_BASE +
					   NEORV32_SYSINFO_CLK));
}

static inline u32 neorv32_sysinfo_get_soc(void)
{
	return readl((void __iomem *)(uintptr_t)(NEORV32_SYSINFO_BASE +
					   NEORV32_SYSINFO_SOC));
}

#endif /* __NEORV32_SYSINFO_H */
