#
# Copyright (C) 2015  Beckhoff Automation GmbH & Co. KG
# Patrick Bruenn <p.bruenn@beckhoff.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y               += mx53cx9020.o
obj-$(CONFIG_VIDEO) += mx53cx9020_video.o
