# SPDX-License-Identifier:	GPL-2.0+
#
# (C) Copyright 2016 Nexell
# Bongyu, KOO <freestyle@nexell.co.kr>

obj-$(CONFIG_PINCTRL_NEXELL) += pinctrl-nexell.o
obj-$(CONFIG_PINCTRL_NEXELL_S5PXX18) += pinctrl-s5pxx18.o
