# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2010 Nobuhiro Iwamatsu
# Copyright (C) 2008 Renesas Solutions Corp.
#
# u-boot/board/shmin/Makefile
#

obj-y	:= shmin.o
extra-y	+= lowlevel_init.o
