# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2015 Thomas Chou <thomas@wytron.com.tw>

obj-y += timer-uclass.o
obj-$(CONFIG_ALTERA_TIMER)	+= altera_timer.o
obj-$(CONFIG_ANDES_PLMT_TIMER) += andes_plmt_timer.o
obj-$(CONFIG_ARC_TIMER)	+= arc_timer.o
obj-$(CONFIG_AST_TIMER)	+= ast_timer.o
obj-$(CONFIG_ATCPIT100_TIMER) += atcpit100_timer.o
obj-$(CONFIG_$(SPL_)ATMEL_PIT_TIMER) += atmel_pit_timer.o
obj-$(CONFIG_$(SPL_)ATMEL_TCB_TIMER) += atmel_tcb_timer.o
obj-$(CONFIG_CADENCE_TTC_TIMER)	+= cadence-ttc.o
obj-$(CONFIG_DESIGNWARE_APB_TIMER)	+= dw-apb-timer.o
obj-$(CONFIG_GXP_TIMER)		+= gxp-timer.o
obj-$(CONFIG_MPC83XX_TIMER) += mpc83xx_timer.o
obj-$(CONFIG_NOMADIK_MTU_TIMER)	+= nomadik-mtu-timer.o
obj-$(CONFIG_NPCM_TIMER)        += npcm-timer.o
obj-$(CONFIG_OMAP_TIMER)	+= omap-timer.o
obj-$(CONFIG_ORION_TIMER)	+= orion-timer.o
obj-$(CONFIG_RENESAS_OSTM_TIMER) += ostm_timer.o
obj-$(CONFIG_RISCV_TIMER) += riscv_timer.o
obj-$(CONFIG_ROCKCHIP_TIMER) += rockchip_timer.o
obj-$(CONFIG_SANDBOX_TIMER)	+= sandbox_timer.o
obj-$(CONFIG_$(SPL_)SIFIVE_CLINT) += sifive_clint_timer.o
obj-$(CONFIG_STI_TIMER)		+= sti-timer.o
obj-$(CONFIG_STM32_TIMER)	+= stm32_timer.o
obj-$(CONFIG_X86_TSC_TIMER)	+= tsc_timer.o
obj-$(CONFIG_MTK_TIMER)		+= mtk_timer.o
obj-$(CONFIG_MCHP_PIT64B_TIMER)	+= mchp-pit64b-timer.o
obj-$(CONFIG_IMX_GPT_TIMER)	+= imx-gpt-timer.o
obj-$(CONFIG_XILINX_TIMER)	+= xilinx-timer.o
