#
# Copyright (C) 2015 Thomas Chou <thomas@wytron.com.tw>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_TIMER)		+= timer-uclass.o
obj-$(CONFIG_ALTERA_TIMER)	+= altera_timer.o
obj-$(CONFIG_SANDBOX_TIMER)	+= sandbox_timer.o
obj-$(CONFIG_X86_TSC_TIMER)	+= tsc_timer.o
obj-$(CONFIG_OMAP_TIMER)	+= omap-timer.o
