#
# Copyright (C) 2015 Thomas Chou <thomas@wytron.com.tw>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += timer-uclass.o
obj-$(CONFIG_ALTERA_TIMER)	+= altera_timer.o
obj-$(CONFIG_SANDBOX_TIMER)	+= sandbox_timer.o
obj-$(CONFIG_X86_TSC_TIMER)	+= tsc_timer.o
obj-$(CONFIG_OMAP_TIMER)	+= omap-timer.o
obj-$(CONFIG_AST_TIMER)	+= ast_timer.o
obj-$(CONFIG_STI_TIMER)		+= sti-timer.o
obj-$(CONFIG_ARC_TIMER)	+= arc_timer.o
obj-$(CONFIG_AG101P_TIMER) += ag101p_timer.o
obj-$(CONFIG_AE3XX_TIMER) += ae3xx_timer.o
obj-$(CONFIG_ROCKCHIP_TIMER) += rockchip_timer.o
obj-$(CONFIG_ATMEL_PIT_TIMER) += atmel_pit_timer.o
