#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y					+= init.o

obj-$(CONFIG_ARCH_UNIPHIER_SLD3)	+= init-sld3.o
obj-$(CONFIG_ARCH_UNIPHIER_LD4)		+= init-ld4.o
obj-$(CONFIG_ARCH_UNIPHIER_PRO4)	+= init-pro4.o
obj-$(CONFIG_ARCH_UNIPHIER_SLD8)	+= init-sld8.o
obj-$(CONFIG_ARCH_UNIPHIER_PRO5)	+= init-pro5.o
obj-$(CONFIG_ARCH_UNIPHIER_PXS2)	+= init-pxs2.o
obj-$(CONFIG_ARCH_UNIPHIER_LD6B)	+= init-pxs2.o
obj-$(CONFIG_ARCH_UNIPHIER_LD11)	+= init-ld11.o
obj-$(CONFIG_ARCH_UNIPHIER_LD20)	+= init-ld20.o
