#
# (C) Copyright 2003-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

# Objects for Xilinx JTAG programming (CPLD)
# CPLD  = ../common/xilinx_jtag/lenval.o \
#	  ../common/xilinx_jtag/micro.o \
#	  ../common/xilinx_jtag/ports.o

# obj-y	= pf5200.o flash.o $(CPLD)
obj-y	= pf5200.o flash.o
