#
# KS2-EVM: board Makefile
# (C) Copyright 2012-2014
#     Texas Instruments Incorporated, <www.ti.com>
# SPDX-License-Identifier:     GPL-2.0+
#

obj-y += board.o
obj-y += ddr3_cfg.o
obj-$(CONFIG_K2HK_EVM) += board_k2hk.o
obj-$(CONFIG_K2HK_EVM) += ddr3_k2hk.o
obj-$(CONFIG_K2E_EVM) += board_k2e.o
obj-$(CONFIG_K2E_EVM) += ddr3_k2e.o
