#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_ARCH_UNIPHIER_SLD3)	+= sbc-sld3.o
obj-$(CONFIG_ARCH_UNIPHIER_LD4)		+= sbc-ld4.o
obj-$(CONFIG_ARCH_UNIPHIER_PRO4)	+= sbc-pro4.o
obj-$(CONFIG_ARCH_UNIPHIER_SLD8)	+= sbc-ld4.o
obj-$(CONFIG_ARCH_UNIPHIER_PRO5)	+= sbc-pro4.o
obj-$(CONFIG_ARCH_UNIPHIER_PXS2)	+= sbc-pxs2.o
obj-$(CONFIG_ARCH_UNIPHIER_LD6B)	+= sbc-pxs2.o
