#
# (C) Copyright 2001-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2002
# Gregory E. Allen, gallen@arlut.utexas.edu
# Matthew E. Karger, karger@arlut.utexas.edu
# Applied Research Laboratories, The University of Texas at Austin
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	= utx8245.o flash.o
