#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y					+= memconf.o
obj-$(CONFIG_ARCH_UNIPHIER_SLD3)	+= memconf-sld3.o
obj-$(CONFIG_ARCH_UNIPHIER_PXS2)	+= memconf-pxs2.o
obj-$(CONFIG_ARCH_UNIPHIER_LD6B)	+= memconf-pxs2.o
obj-$(CONFIG_ARCH_UNIPHIER_LD20)	+= memconf-pxs2.o
