#
# Copyright (c) 2015 Google, Inc
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:      GPL-2.0+
#
obj-$(CONFIG_CPU) += cpu-uclass.o

obj-$(CONFIG_ARCH_BMIPS) += bmips_cpu.o
