# SPDX-License-Identifier: GPL-2.0

# Core
obj-$(CONFIG_PINCTRL_MTMIPS) += pinctrl-mtmips-common.o

# SoC Drivers
obj-$(CONFIG_PINCTRL_MT7620) += pinctrl-mt7620.o
obj-$(CONFIG_PINCTRL_MT7621) += pinctrl-mt7621.o
obj-$(CONFIG_PINCTRL_MT7628) += pinctrl-mt7628.o
