#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2015
# Kamil Lulko, <kamil.lulko@gmail.com>
#
# Copyright 2015 ATS Advanced Telematics Systems GmbH
# Copyright 2015 Konsulko Group, Matt Porter <mporter@konsulko.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += soc.o clock.o timer.o flash.o
