#
# (C) Copyright 2014  DENX Software Engineering GmbH
# Written-by: Albert ARIBAUD <albert.aribaud@3adev.fr>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= work_92105.o work_92105_display.o

obj-$(CONFIG_SPL_BUILD) += work_92105_spl.o
