# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2025 Texas Instruments Incorporated - https://www.ti.com/
#	Andrew Davis <afd@ti.com>

obj-$(CONFIG_OF_SYSTEM_SETUP) += ../j721e/j721e_fdt.o
obj-$(CONFIG_XPL_BUILD) += ../j721e/j721e_init.o
