# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2010-2012, NVIDIA CORPORATION.  All rights reserved.

obj-$(CONFIG_SPL_BUILD) += cpu.o
obj-$(CONFIG_$(SPL_)CMD_EBTUPDATE) += bct.o

obj-y	+= clock.o
