#
# board/renesas/silk/Makefile
#
# Copyright (C) 2015 Renesas Electronics Corporation
# Copyright (C) 2015 Cogent Embedded, Inc.
#
# SPDX-License-Identifier: GPL-2.0
#

obj-y	:= silk.o qos.o ../rcar-common/common.o
