#
# Copyright (C) 2017 Microchip
#		      Wenyou Yang <wenyou.yang@microchip.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += board.o
obj-$(CONFIG_I2C_EEPROM) += mac_eeprom.o
obj-$(CONFIG_DM_VIDEO) += video_display.o
