#
# (C) Copyright 2017 Theobroma Systems Design und Consulting GmbH
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-y	+= puma-rk3399.o
ifneq ($(CONFIG_XPL_BUILD),y)
obj-y	+= ../common/common.o
endif
