#
# (C) Copyright 2010
# Stefan Roese, DENX Software Engineering, sr@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= t3corp.o
obj-$(CONFIG_CMD_CHIP_CONFIG) += chip_config.o
extra-y += init.o
