# SPDX-License-Identifier:     GPL-2.0+
#
# https://beagleboard.org/ai-64
#
# Copyright (C) 2022-2023 Texas Instruments Incorporated - https://www.ti.com/
# Copyright (C) 2022-2023 Jason Kridner, BeagleBoard.org Foundation
# Copyright (C) 2022-2023 Robert Nelson, BeagleBoard.org Foundation
#

obj-y	+= beagleboneai64.o
