#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# Copyright 2004 Picture Elements, Inc.
# Stephen Williams <steve@icarus.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	= jse.o sdram.o flash.o host_bridge.o
obj-y	+= init.o
