#
# Copyright (C) 2017 Andes Technology Corporation.
# Rick Chen, Andes Technology Corporation <rick@andestech.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

head-y := arch/riscv/cpu/$(CPU)/start.o

libs-y += arch/riscv/cpu/$(CPU)/
libs-y += arch/riscv/lib/
