#
# (C) Copyright 2012 Stephen Warren
#
# SPDX-License-Identifier:	GPL-2.0+
#

src_dir := ../../arm1176/bcm2835/

obj-y	:=
obj-y	+= $(src_dir)/init.o
obj-y	+= $(src_dir)/reset.o
obj-y	+= $(src_dir)/timer.o
obj-y	+= $(src_dir)/mbox.o
