#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_CMD_CRAMFS) := cramfs.o
obj-$(CONFIG_CMD_CRAMFS) += uncompress.o
