# SPDX-License-Identifier: GPL-2.0+
#
# Copyright 2022-2023 Arm Limited and/or its affiliates <open-source-office@arm.com>
#
# Authors:
#   Abdellatif El Khlifi <abdellatif.elkhlifi@arm.com>

obj-y += arm-ffa-uclass.o arm-ffa.o
