# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2010-2013, NVIDIA CORPORATION.  All rights reserved.
#
# Copyright (c) 2023, Svyatoslav Ryhel <clamor95@gmail.com>
#

obj-$(CONFIG_XPL_BUILD) += tegratab-spl.o

obj-y += tegratab.o
