#
# (C) Copyright 2022 Theobroma Systems Design und Consulting GmbH
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-y	+= ringneck-px30.o
ifneq ($(CONFIG_SPL_BUILD),y)
obj-y	+= ../common/common.o
endif
