#
# (C) Copyright 2000-2008
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2013
# Bo Shen <voice.shen@atmel.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_SAMA5D3)	+= sama5d3_devices.o
obj-y += clock.o
obj-y += cpu.o
obj-y += reset.o
obj-y += timer.o
