# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_BOOTCOUNT_GENERIC)	+= bootcount.o
obj-$(CONFIG_BOOTCOUNT_MEM)	+= bootcount.o
obj-$(CONFIG_BOOTCOUNT_AT91)	+= bootcount_at91.o
obj-$(CONFIG_BOOTCOUNT_AM33XX)	+= bootcount_davinci.o
obj-$(CONFIG_BOOTCOUNT_RAM)	+= bootcount_ram.o
obj-$(CONFIG_BOOTCOUNT_ENV)	+= bootcount_env.o
obj-$(CONFIG_BOOTCOUNT_FS)	+= bootcount_fs.o
obj-$(CONFIG_BOOTCOUNT_AM33XX_NVMEM)	+= bootcount_nvmem.o

obj-$(CONFIG_DM_BOOTCOUNT)      += bootcount-uclass.o
obj-$(CONFIG_DM_BOOTCOUNT_PMIC_PFUZE100) += pmic_pfuze100.o
obj-$(CONFIG_DM_BOOTCOUNT_RTC)  += rtc.o
obj-$(CONFIG_DM_BOOTCOUNT_I2C_EEPROM)	+= i2c-eeprom.o
obj-$(CONFIG_DM_BOOTCOUNT_I2C)	+= bootcount_dm_i2c.o
obj-$(CONFIG_DM_BOOTCOUNT_SPI_FLASH)	+= spi-flash.o
obj-$(CONFIG_DM_BOOTCOUNT_SYSCON) += bootcount_syscon.o
