#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y				+= bootcount.o
obj-$(CONFIG_AT91SAM9XE)	+= bootcount_at91.o
obj-$(CONFIG_BLACKFIN)		+= bootcount_blackfin.o
obj-$(CONFIG_SOC_DA8XX)		+= bootcount_davinci.o
obj-$(CONFIG_AM33XX)		+= bootcount_davinci.o
obj-$(CONFIG_BOOTCOUNT_RAM)	+= bootcount_ram.o
