#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_ARCH_UNIPHIER_SLD3)	+= pinctrl-sld3.o
obj-$(CONFIG_ARCH_UNIPHIER_LD4)		+= pinctrl-ld4.o
obj-$(CONFIG_ARCH_UNIPHIER_PRO4)	+= pinctrl-pro4.o
obj-$(CONFIG_ARCH_UNIPHIER_SLD8)	+= pinctrl-sld8.o
obj-$(CONFIG_ARCH_UNIPHIER_PRO5)	+= pinctrl-pro5.o
obj-$(CONFIG_ARCH_UNIPHIER_PXS2)	+= pinctrl-pxs2.o
obj-$(CONFIG_ARCH_UNIPHIER_LD6B)	+= pinctrl-ld6b.o
obj-$(CONFIG_ARCH_UNIPHIER_LD11)	+= pinctrl-ld20.o
obj-$(CONFIG_ARCH_UNIPHIER_LD20)	+= pinctrl-ld20.o
