#
# Copyright (C) STMicroelectronics SA 2017
#
# Authors: Philippe Cornu <philippe.cornu@st.com>
#          Yannick Fertre <yannick.fertre@st.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-${CONFIG_VIDEO_STM32} = stm32_ltdc.o
