# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2011 - 2013 CompuLab, Ltd. <www.compulab.co.il>
#
# Author: Igor Grinberg <grinberg@compulab.co.il>

obj-y				+= common.o
obj-$(CONFIG_$(SPL_)SYS_I2C_LEGACY)	+= eeprom.o
obj-$(CONFIG_SMC911X)		+= omap3_smc911x.o
