# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2016 Nexell
# Hyunseok, Jung <hsjung@nexell.co.kr>
#
# Copyright (C) 2023  Stefan Bosch <stefan_b@posteo.net>

obj-y += cpu.o
obj-y += relocate.o
