#
# Copyright 2015 Freescale Semiconductor
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += ddr.o
obj-y += ls1043ardb.o
ifndef CONFIG_SPL_BUILD
obj-$(CONFIG_SYS_DPAA_FMAN) += eth.o
obj-y += cpld.o
endif
