# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2010-2017 CS Systemes d'Information
# Christophe Leroy <christophe.leroy@c-s.fr>
#

obj-y += mcr3000.o
obj-$(CONFIG_CMD_NAND) += nand.o
obj-$(CONFIG_MPC8XX_SPI) += mcr3000_gpio.o
