#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

extra-y	= start.o
obj-y	= exceptions.o
obj-y	+= cpu.o interrupts.o traps.o
obj-y	+= fdt.o
