#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2002
# Daniel Engström, Omicron Ceti AB, daniel@omicron.se.
#
# SPDX-License-Identifier:	GPL-2.0+
#

extra-y	= start.o
extra-$(CONFIG_X86_RESET_VECTOR) += resetvec.o start16.o
obj-y	= interrupts.o cpu.o
