#
# board/mx1ads/Makefile
#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (c) Copyright 2004
# Techware Information Technology, Inc.
# http://www.techware.com.tw/
#
# Ming-Len Wu <minglen_wu@techware.com.tw>
#
# SPDX-License-Identifier:	GPL-2.0+

obj-y	:= mx1ads.o syncflash.o
obj-y	+= lowlevel_init.o
