#
# (C) Copyright 2003-2008
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2008
# Stelian Pop <stelian@popies.net
# Lead Tech Design <www.leadtechdesign.com>
# Ilko Iliev <www.ronetix.at>
#
# (C) Copyright 2009
# Eric Benard <eric@eukrea.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += cpu9260.o
obj-y += led.o
