#
# (C) Copyright 2002-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	= sequoia.o sdram.o
obj-$(CONFIG_CMD_CHIP_CONFIG) += chip_config.o
extra-y	+= init.o
