# (C) Copyright 2019 Marvell, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += lowlevel_init.o
obj-y += cache.o
obj-y += clock.o
obj-y += cpu.o
obj-y += dram.o
obj-y += cvmx-coremask.o
obj-y += cvmx-bootmem.o
obj-y += bootoctlinux.o

# QLM related code
obj-y += cvmx-helper-cfg.o
obj-y += cvmx-helper-fdt.o
obj-y += cvmx-helper-jtag.o
obj-y += cvmx-helper-util.o
obj-y += cvmx-helper.o
obj-y += cvmx-pcie.o
obj-y += cvmx-qlm.o
obj-y += octeon_fdt.o
obj-y += octeon_qlm.o
