# (C) Copyright 2019 Marvell, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += lowlevel_init.o
obj-y += cache.o
obj-y += clock.o
obj-y += cpu.o
obj-y += dram.o
obj-y += cvmx-coremask.o
obj-y += cvmx-bootmem.o
obj-y += bootoctlinux.o
