# (C) Copyright 2019 Marvell, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += lowlevel_init.o
obj-y += cache.o
obj-y += clock.o
obj-y += cpu.o
obj-y += dram.o
obj-y += cvmx-coremask.o
obj-y += cvmx-bootmem.o
obj-y += bootoctlinux.o

# Misc Octeon C files, mostly for QLM & ethernet support
obj-y += cvmx-agl.o
obj-y += cvmx-fpa.o
obj-y += cvmx-fpa-resource.o
obj-y += cvmx-fau-compat.o
obj-y += cvmx-global-resources.o
obj-y += cvmx-cmd-queue.o
obj-y += cvmx-helper-agl.o
obj-y += cvmx-helper-bgx.o
obj-y += cvmx-helper-board.o
obj-y += cvmx-helper-cfg.o
obj-y += cvmx-helper-fdt.o
obj-y += cvmx-helper-fpa.o
obj-y += cvmx-helper-ilk.o
obj-y += cvmx-helper-ipd.o
obj-y += cvmx-helper-jtag.o
obj-y += cvmx-helper-loop.o
obj-y += cvmx-helper-npi.o
obj-y += cvmx-helper-pki.o
obj-y += cvmx-helper-pko.o
obj-y += cvmx-helper-pko3.o
obj-y += cvmx-helper-rgmii.o
obj-y += cvmx-helper-sfp.o
obj-y += cvmx-helper-sgmii.o
obj-y += cvmx-helper-util.o
obj-y += cvmx-helper-xaui.o
obj-y += cvmx-helper.o
obj-y += cvmx-ilk.o
obj-y += cvmx-ipd.o
obj-y += cvmx-pcie.o
obj-y += cvmx-pki.o
obj-y += cvmx-pki-resources.o
obj-y += cvmx-pko.o
obj-y += cvmx-pko-internal-ports-range.o
obj-y += cvmx-pko3.o
obj-y += cvmx-pko3-compat.o
obj-y += cvmx-pko3-resources.o
obj-y += cvmx-pko3-queue.o
obj-y += cvmx-range.o
obj-y += cvmx-qlm.o
obj-y += cvmx-qlm-tables.o
obj-y += octeon_fdt.o
obj-y += octeon_qlm.o
