# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the bus drivers.
#

obj-$(CONFIG_TI_PWMSS)	+= ti-pwmss.o
obj-$(CONFIG_TI_SYSC)	+= ti-sysc.o
obj-$(CONFIG_UNIPHIER_SYSTEM_BUS) += uniphier-system-bus.o
