#
#  (C) Copyright 2010,2011
#  NVIDIA Corporation <www.nvidia.com>
#  (C) Copyright 2011,2012
#  Avionic Design GmbH <www.avionic-design.de>
#
# SPDX-License-Identifier:	GPL-2.0+
#

$(shell mkdir -p $(obj)../common $(obj)../../nvidia/common)

obj-y	:= ../common/tamonten.o

include ../../nvidia/common/common.mk
