# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2014-2021 Tony Dinh <mibodhi@gmail.com>
#
# Based on
# Marvell Semiconductor <www.marvell.com>
# Written-by: Prafulla Wadaskar <prafulla@marvell.com>
#

obj-y	:= pogo_v4.o
