obj-y	+= scmi_agent-uclass.o
obj-y	+= base.o
obj-y	+= smt.o
obj-$(CONFIG_SCMI_AGENT_SMCCC)		+= smccc_agent.o
obj-$(CONFIG_SCMI_AGENT_MAILBOX)	+= mailbox_agent.o
obj-$(CONFIG_SCMI_AGENT_OPTEE)	+= optee_agent.o
obj-$(CONFIG_SCMI_POWER_DOMAIN)		+= pwdom.o
obj-$(CONFIG_SANDBOX)		+= sandbox-scmi_agent.o sandbox-scmi_devices.o
