#
# (C) Copyright 2002-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	= pmc440.o cmd_pmc440.o sdram.o fpga.o \
	../common/cmd_loadpci.o
extra-y	+= init.o
