#
# board/renesas/whitehawk/Makefile
#
# Copyright (C) 2021 Renesas Electronics Corp.
#
# SPDX-License-Identifier: GPL-2.0+
#

ifdef CONFIG_SPL_BUILD
obj-y	:= ../common/gen4-spl.o
else
obj-y	:= ../common/gen4-common.o ../common/common.o
endif
