# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2016 Marvell International Ltd.
#
# https://spdx.org/licenses

ccflags-y += -Idrivers/mtd/nand/raw/

obj-$(CONFIG_CMD_MVEBU_BUBT) += bubt.o
obj-$(CONFIG_CMD_MVEBU_RX_TRAINING) += rx_training.o
obj-$(CONFIG_CMD_MVEBU_AVS) += avs.o
obj-$(CONFIG_CMD_MVEBU_EFUSE) += efuse.o
obj-$(CONFIG_CMD_MVEBU_MAP) += map.o
obj-$(CONFIG_CMD_MVEBU_NAND_OEM) += pxa3xx_nand_oem.o
obj-$(CONFIG_CMD_MVEBU_TSEN) += thermal.o
obj-$(CONFIG_CMD_MVEBU_HW_INFO) += hw_info.o
obj-$(CONFIG_CMD_MVEBU_SAR) += sar.o
obj-$(CONFIG_CMD_MVEBU_MV_FW_INFO) += mv_fw_info.o
obj-$(CONFIG_CMD_MVEBU_MV_GET_COUNTERS) += mv_get_counters.o
obj-$(CONFIG_CMD_MVEBU_DDR_PHY) += ddr_phy.o
obj-$(CONFIG_CMD_MV88E6XXX_UTIL) += mv88e6xxx-util.o