# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2016 Marvell International Ltd.
#
# https://spdx.org/licenses

obj-$(CONFIG_CMD_MVEBU_BUBT) += bubt.o
obj-$(CONFIG_CMD_MVEBU_COMPHY_RX_TRAINING) += comphy_rx_training.o
