#
# (C) Copyright 2001-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= stxgp3.o
obj-y	+= law.o
obj-y	+= tlb.o
obj-y	+= flash.o
obj-$(CONFIG_SYS_FSL_DDR1) += ddr.o
