# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2019, Theobroma Systems Design und Consulting GmbH

# Test files
obj-y += cmd_ut_optee.o

DTC_FLAGS += -@

# DT overlays
obj-y += test-optee-base.dtb.o
obj-y += test-optee-optee.dtb.o
obj-y += test-optee-no-optee.dtb.o
