#
# (C) Copyright 2002-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

CPPFLAGS += -I$(TOPDIR)

obj-$(CONFIG_HAS_POST)	+= flash.o i2c.o memory.o rtc.o
