#
# (C) Copyright 2001-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# Copyright (C) 2011
# Corscience GmbH & Co.KG, Andreas Bießmann <biessmann@corscience.de>
#
# SPDX-License-Identifier:	GPL-2.0+

obj-y += grasshopper.o
