# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2024 CS GROUP France
# Christophe Leroy <christophe.leroy@csgroup.eu>
#

obj-$(CONFIG_TARGET_CMPC885) += common.o
obj-$(CONFIG_TARGET_CMPCPRO) += common.o
