# Copyright 2007 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= mpc8610hpcd.o
obj-$(CONFIG_SYS_FSL_DDR2) += ddr.o
obj-y	+= law.o
obj-$(CONFIG_FSL_DIU_FB)	+= mpc8610hpcd_diu.o
