#
# Copyright (C) 2016 Marvell International Ltd.
#
# SPDX-License-Identifier:	GPL-2.0
# https://spdx.org/licenses

obj-$(CONFIG_PINCTRL_ARMADA_37XX) += pinctrl-armada-37xx.o
obj-$(CONFIG_PINCTRL_ARMADA_8K)	+= pinctrl-mvebu.o
