#
# Copyright (C) 2012 Samsung Electronics
# R. Chandrasekar <rcsekar@samsung.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_SOUND)	+= sound.o
obj-$(CONFIG_I2S)	+= sound-i2s.o
obj-$(CONFIG_I2S_SAMSUNG)	+= samsung-i2s.o
obj-$(CONFIG_SOUND_SANDBOX)	+= sandbox.o
obj-$(CONFIG_SOUND_WM8994)	+= wm8994.o
obj-$(CONFIG_SOUND_MAX98095)	+= max98095.o
