#
# Copyright (C) 2008 Renesas Solutions Corp.
# Copyright (C) 2008 Nobuhiro Iwamatsu <iwamatsu.nobuhiro@renesas.com>
# Copyright (C) 2007 Kenati Technologies, Inc.
#
# board/sh7763rdp/Makefile
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= sh7763rdp.o
obj-y	+= lowlevel_init.o
