# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2017, STMicroelectronics - All Rights Reserved
# Author(s): Patrice CHOTARD, <patrice.chotard@foss.st.com> for STMicroelectronics.

obj-y	:= stm32h743-disco.o
