#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_DISPLAY_CPUINFO)	+= cpu_info.o
obj-y	+= speed.o
obj-y	+= timer.o
