#
# U-Boot - Makefile
#
# Copyright (c) Switchfin Org. <dpn@switchfin.org>
#
# Copyright (c) 2005-2007 Analog Device Inc.
#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= br4.o
