#
# Copyright 2010 Freescale Semiconductor, Inc.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#

obj-y	+= law.o
obj-y	+= ddr.o
obj-y	+= tlb.o
obj-y	+= sdhc_boot.o
obj-$(CONFIG_CONTROLCENTERD) += controlcenterd.o controlcenterd-id.o
obj-$(CONFIG_FSL_DIU_FB) += diu.o
