# SPDX-License-Identifier: GPL-2.0+
#
#  (C) Copyright 2010-2012
#  NVIDIA Corporation <www.nvidia.com>
#
#  (C) Copyright 2023
#  Svyatoslav Ryhel <clamor95@gmail.com>

obj-$(CONFIG_SPL_BUILD) += qc750-spl.o

obj-y += qc750.o
