#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2001
# Josh Huber <huber@mclx.com>, Mission Critical Linux, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	= db64360.o ../common/flash.o ../common/serial.o ../common/memory.o pci.o \
	  mv_eth.o ../common/ns16550.o mpsc.o ../common/i2c.o \
	  sdram_init.o ../common/intel_flash.o ../common/misc.o
