#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += mpc8349emds.o
obj-$(CONFIG_PCI) += pci.o
obj-$(CONFIG_SYS_FSL_DDR2) += ddr.o
