#
# Copyright 2014 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier: GPL-2.0+
#

obj-$(CONFIG_T4240RDB) += t4240rdb.o
obj-y	+= ddr.o
obj-y	+= eth.o
obj-$(CONFIG_PCI)	+= pci.o
obj-y	+= law.o
obj-y	+= tlb.o
