# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2024, STMicroelectronics - All Rights Reserved

obj-y += stm32-reset-core.o

obj-$(CONFIG_RESET_STM32) += stm32-reset.o
obj-$(CONFIG_RESET_STM32MP1) += stm32-reset-mp1.o
obj-$(CONFIG_RESET_STM32MP25) += stm32-reset-mp25.o
