#
# (C) Copyright 2000-2010
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= hwinit.o
obj-y	+= emif.o
obj-y	+= sdram.o
obj-y	+= prcm-regs.o
obj-y	+= hw_data.o
obj-y	+= abb.o
