obj-$(CONFIG_FIRMWARE)		+= firmware-uclass.o
obj-$(CONFIG_$(SPL_)ARM_PSCI_FW)	+= psci.o
obj-$(CONFIG_TI_SCI_PROTOCOL)	+= ti_sci.o
obj-$(CONFIG_SANDBOX)		+= firmware-sandbox.o
obj-$(CONFIG_ZYNQMP_FIRMWARE)	+= firmware-zynqmp.o
