#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2001
# Josh Huber <huber@mclx.com>, Mission Critical Linux, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	= misc.o
obj-y	+= evb64260.o flash.o serial.o memory.o pci.o \
	  eth.o eth_addrtbl.o mpsc.o i2c.o \
	  sdram_init.o zuma_pbb.o intel_flash.o zuma_pbb_mbox.o
