#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2013
# Heiko Schocher, DENX Software Engineering, <hs@denx.de>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	= ids8313.o
