# SPDX-License-Identifier: GPL-2.0+
#
# 2017 Marek Behún, CZ.NIC, kabel@kernel.org

obj-y := btrfs.o compression.o ctree.o dev.o dir-item.o \
	extent-io.o inode.o subvolume.o crypto/hash.o disk-io.o \
	common/rbtree-utils.o extent-cache.o volumes.o root-tree.o
