#
# 2017 Marek Behun, CZ.NIC, marek.behun@nic.cz
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y := btrfs.o chunk-map.o compression.o ctree.o dev.o dir-item.o \
	extent-io.o hash.o inode.o root.o subvolume.o super.o
