# SPDX-License-Identifier: GPL-2.0+
#
# 2017 Marek Behun, CZ.NIC, marek.behun@nic.cz

obj-y := btrfs.o chunk-map.o compression.o ctree.o dev.o dir-item.o \
	extent-io.o inode.o root.o subvolume.o super.o crypto/hash.o disk-io.o
