#
# (C) Copyright 2009
# Marvell Semiconductor <www.marvell.com>
# Written-by: Prafulla Wadaskar <prafulla@marvell.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	= cpu.o
obj-y	+= dram.o
obj-y	+= mpp.o
obj-y	+= timer.o
obj-y	+= cache.o
