#
# Copyright (C) 2022 Marek Vasut <marex@denx.de>
#
# SPDX-License-Identifier:      GPL-2.0+
#

ifdef CONFIG_XPL_BUILD
obj-y += spl.o lpddr4_timing_4G_32.o
else
obj-y += imx8mp_data_modul_edm_sbc.o
endif

obj-y += ../common/common.o
