# Copyright (c) 2016, NVIDIA CORPORATION.
#
# SPDX-License-Identifier: GPL-2.0

obj-y += ../arm64-mmu.o
obj-y += ../board186.o
obj-y += ../lowlevel_init.o
obj-$(CONFIG_DISPLAY_CPUINFO) += ../sys_info.o
