#/*
# * Copyright (C) 2018 Marvell International Ltd.
# *
# * SPDX-License-Identifier:    GPL-2.0
# * https://spdx.org/licenses
# */


obj-$(CONFIG_NET_OCTEONTX2) += cgx.o nix_af.o nix.o rvu_pf.o \
				rvu_af.o rvu_common.o

