# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2016 Freescale Semiconductor, Inc.
#

obj-$(CONFIG_$(SPL_)DM_USB) += common.o
obj-$(CONFIG_USB_ISP1760) += usb_urb.o
obj-$(CONFIG_USB_MUSB_HOST) += usb_urb.o
obj-$(CONFIG_USB_MUSB_GADGET) += usb_urb.o
obj-$(CONFIG_USB_R8A66597_HCD) += usb_urb.o
obj-$(CONFIG_USB_EHCI_FSL) += fsl-dt-fixup.o fsl-errata.o
obj-$(CONFIG_USB_XHCI_FSL) += fsl-dt-fixup.o fsl-errata.o
