# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2022, Linaro Limited
#

obj-$(CONFIG_DM_FWU_MDATA) += fwu-mdata-uclass.o
obj-$(CONFIG_FWU_MDATA_GPT_BLK) += fwu_mdata_gpt_blk.o
obj-$(CONFIG_FWU_MDATA_MTD) += fwu_mdata_mtd.o
