#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2002 Wolfgang Grandegger <wg@denx.de>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= iphase4539.o flash.o
