#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	= voh405.o flash.o \
	../common/misc.o \
	../common/esd405ep_nand.o \
