#
# Copyright (C) 2013 Compulab Ltd - http://compulab.co.il/
#
# Author: Ilya Ledvich <ilya@compulab.co.il>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= $(BOARD).o
obj-$(CONFIG_SPL_BUILD) += mux.o spl.o
