#
# Copyright (C) 2013-2014 Synopsys, Inc. All rights reserved.
#
# SPDX-License-Identifier:	GPL-2.0+
#

extra-y	+= start.o

obj-y	+= cache.o
obj-y	+= cpu.o
obj-y	+= interrupts.o
obj-y	+= reset.o
obj-y	+= timer.o
