# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2019
# Ramon Fried <ramon.fried@gmail.com>

obj-y += pci_ep-uclass.o
obj-$(CONFIG_PCIE_CADENCE_EP) += pcie-cadence-ep.o
obj-$(CONFIG_PCI_SANDBOX_EP) += sandbox-pci_ep.o
obj-$(CONFIG_PCIE_CDNS_TI_EP) += pcie_cdns_ti_ep.o
