#
# Copyright (C) 2017, STMicroelectronics - All Rights Reserved
# Author(s): Patrice CHOTARD, <patrice.chotard@st.com> for STMicroelectronics.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += soc.o
