#
#  (C) Copyright 2010-2012
#  NVIDIA Corporation <www.nvidia.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

$(shell mkdir -p $(obj)../../nvidia/common)

obj-y	:= trimslice.o

include ../../nvidia/common/common.mk
