# SPDX-License-Identifier: GPL-2.0+
#
# Copyright 2025 NXP

# Add include path for NXP device tree header files from Linux.
ccflags-y += -I$(srctree)/dts/upstream/src/arm64/freescale/

obj-y += soc.o
obj-y += clock_scmi.o clock.o
