#
# (C) Copyright 2013 Freescale Semiconductor, Inc.
# Copyright (C) 2013, Boundary Devices <info@boundarydevices.com>
# Copyright (C) 2013, Jon Nettleton <jon.nettleton@gmail.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y  := hummingboard.o
