# SPDX-License-Identifier:	GPL-2.0+
# (C) Copyright 2016 Keymile AG
# Rainer Boschung <rainer.boschung@keymile.com>
#
# Copyright 2013 Freescale Semiconductor, Inc.
#

obj-y	+= kmcent2.o
obj-y	+= ddr.o
obj-y	+= law.o
obj-y	+= tlb.o
obj-y	+= ../common/common.o
obj-y	+= ../common/ivm.o
obj-y	+= ../common/qrio.o
