#/*
# * Copyright (C) 2018 Marvell International Ltd.
# *
# * SPDX-License-Identifier:    GPL-2.0
# * https://spdx.org/licenses
# */

obj-y	:= board.o smc.o soc-utils.o
obj-$(CONFIG_OF_LIBFDT) += board-fdt.o
