#
# (C) Copyright 2009-2010
# Stefan Roese, DENX Software Engineering, sr@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= icon.o
obj-$(CONFIG_CMD_CHIP_CONFIG) += chip_config.o
extra-y	+= init.o
