#
# Copyright (c) 2012, Google Inc.
#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2003
# Pavel Bartusek, Sysgo Real-Time Solutions AG, pba@sysgo.de
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y := sandboxfs.o
