#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y   = cpu.o clk.o devices.o timer.o

obj-$(CONFIG_SPL_BUILD) += dram.o lowlevel_init.o
