# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2024 Texas Instruments Incorporated - https://www.ti.com/
#	Andrew Davis <afd@ti.com>

obj-$(CONFIG_OF_SYSTEM_SETUP) += am62a7_fdt.o
obj-$(CONFIG_XPL_BUILD) += am62a7_init.o
obj-y += boot.o
