# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2025 Linaro Limited
#

obj-$(CONFIG_$(PHASE_)INTERCONNECT_QCOM_RPMH) += icc-rpmh.o bcm-voter.o
obj-$(CONFIG_$(PHASE_)INTERCONNECT_QCOM_SM8650) += sm8650.o
