# SPDX-License-Identifier:     GPL-2.0+
#
# Copyright (C) 2021 PHYTEC America, LLC - https://www.phytec.com
# Author: Matt McKee <mmckee@phytec.com>
#
# Copyright (C) 2022 - 2024 PHYTEC Messtechnik GmbH
# Author: Wadim Egorov <w.egorov@phytec.de>

obj-y += phycore-am64x.o
