# Copyright (c) 2011 The Chromium OS Authors. All rights reserved.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_TPM) += tpm-uclass.o

obj-$(CONFIG_TPM_ATMEL_TWI) += tpm_atmel_twi.o
obj-$(CONFIG_TPM_TIS_INFINEON) += tpm_tis_infineon.o
obj-$(CONFIG_TPM_TIS_LPC) += tpm_tis_lpc.o
obj-$(CONFIG_TPM_TIS_SANDBOX) += tpm_tis_sandbox.o
