#
#  Copyright (C) 2015 Google, Inc
#  Written by Simon Glass <sjg@chromium.org>
#
#  SPDX-License-Identifier:	GPL-2.0+

obj-$(CONFIG_VIDEO_BRIDGE) += video-bridge-uclass.o
obj-$(CONFIG_VIDEO_BRIDGE_PARADE_PS862X) += ps862x.o
obj-$(CONFIG_VIDEO_BRIDGE_NXP_PTN3460) += ptn3460.o
