#
# Makefile
#
# Copyright (C) 2013 Hannes Petermaier <oe5hpm@oevsv.at>
# Bernecker & Rainer Industrieelektronik GmbH - http://www.br-automation.com
#
# SPDX-License-Identifier:	GPL-2.0+
#

ifeq ($(CONFIG_SPL_BUILD),y)
obj-y	:= mux.o
endif
obj-y	+= ../common/common.o
obj-y	+= board.o
