#
# (C) Copyright 2003-2008
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2008
# Stelian Pop <stelian@popies.net>
# Lead Tech Design <www.leadtechdesign.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += at91sam9261ek.o
obj-y += led.o
obj-$(CONFIG_HAS_DATAFLASH) += partition.o
