#
# Copyright (C) 2007
# Nobuhiro Iwamatsu <iwamatsu@nigauri.org>
#
# Copyright (C) 2007
# Kenati Technologies, Inc.
#
# board/ms7722se/Makefile
#
# SPDX-License-Identifier:	GPL-2.0+

obj-y	:= ms7722se.o
obj-y	+= lowlevel_init.o
