#
# Copyright (C) 2018 Marvell International Ltd.
#
# SPDX-License-Identifier: GPL-2.0+
# https://spdx.org/licenses
#

obj-$(CONFIG_BOARD_CONFIG_EEPROM)	+= cfg_eeprom.o
obj-$(CONFIG_MVEBU_SAR)	+= sar.o
