#
# (C) Copyright 2007
# Stefan Roese, DENX Software Engineering, sr@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y := 405ex.o
obj-$(CONFIG_IO64) += io64.o
obj-$(CONFIG_CMD_CHIP_CONFIG) += chip_config.o
