#
# Copyright (C) 2007, Guennadi Liakhovetski <lg@denx.de>
#
# (C) Copyright 2011 Freescale Semiconductor, Inc.
# (C) Copyright 2013 Adeneo Embedded <www.adeneo-embedded.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y  := cgtqmx6eval.o
