# SPDX-License-Identifier:	GPL-2.0+
#
# Copyright (C) 2019 Hannes Schmelzer <oe5hpm@oevsv.at> -
# B&R Industrial Automation GmbH - http://www.br-automation.com/
#

obj-$(CONFIG_SPL_BUILD) += mux.o
obj-y	+= ../common/br_resetc.o
obj-y	+= ../common/common.o
obj-y	+= board.o
