#
# board/renesas/falcon/Makefile
#
# Copyright (C) 2020 Renesas Electronics Corp.
#
# SPDX-License-Identifier: GPL-2.0+
#

ifndef CONFIG_XPL_BUILD
obj-y	:= ../common/gen4-common.o ../common/common.o
endif
