#
# board/renesas/falcon/Makefile
#
# Copyright (C) 2020 Renesas Electronics Corp.
#
# SPDX-License-Identifier: GPL-2.0+
#

ifdef CONFIG_XPL_BUILD
obj-y	:= ../rcar-common/gen3-spl.o
else
obj-y	:= ../rcar-common/gen4-common.o ../rcar-common/common.o
endif
