#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

#ccflags-y += -DET_DEBUG -DDEBUG

obj-$(CONFIG_PARTITIONS) 	+= part.o
obj-$(CONFIG_MAC_PARTITION)   += part_mac.o
obj-$(CONFIG_DOS_PARTITION)   += part_dos.o
obj-$(CONFIG_ISO_PARTITION)   += part_iso.o
obj-$(CONFIG_AMIGA_PARTITION) += part_amiga.o
obj-$(CONFIG_EFI_PARTITION)   += part_efi.o
