#
# Copyright 2007-2009 Freescale Semiconductor, Inc.
# (C) Copyright 2001-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= hww1u1a.o
obj-y	+= law.o
obj-y	+= tlb.o
obj-$(CONFIG_DDR_SPD) += ddr.o
