ccflags-y += -I$(srctree)/net/lwip/port/include
ccflags-y += -I$(srctree)/net/lwip/lwip-external/src/include -I$(srctree)/net/lwip
ccflags-y += -I$(srctree)/net/lwip/lwip-external/src/include/lwip/apps
ccflags-y += -I$(srctree)/net/lwip/lwip-external/contrib/examples/tftp/

obj-y += ../../lwip-external/src/apps/tftp/tftp.o
obj-y += lwip-tftp.o
