# SPDX-License-Identifier: GPL-2.0+
#
# Makefile for AM625 PocketBeagle 2
# https://www.beagleboard.org/boards/pocketbeagle-2
#
# Copyright (C) 2025 Texas Instruments Incorporated - https://www.ti.com/
#

obj-y += pocketbeagle2.o
obj-${CONFIG_K3_DDRSS} += ../../phytec/common/k3/k3_ddrss_patch.o
obj-${CONFIG_TI_I2C_BOARD_DETECT} += ../../ti/common/board_detect.o
