# SPDX-License-Identifier: GPL-2.0+
#
# Makefile for AM625 PocketBeagle 2
# https://www.beagleboard.org/boards/pocketbeagle-2
#
# Copyright (C) 2025 Texas Instruments Incorporated - https://www.ti.com/
#

obj-y += pocketbeagle2.o
