# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2014 Freescale Semiconductor, Inc.
# Author: Nitin Garg <nitin.garg@freescale.com>

obj-$(CONFIG_DM_THERMAL) += thermal-uclass.o
obj-$(CONFIG_IMX_THERMAL) += imx_thermal.o
obj-$(CONFIG_IMX_SCU_THERMAL) += imx_scu_thermal.o
obj-$(CONFIG_TI_DRA7_THERMAL) += ti-bandgap.o
obj-$(CONFIG_MVEBU_THERMAL_SENSOR) += mvebu_thermal_core.o
obj-$(CONFIG_MVEBU_THERMAL_SENSOR_28NM) += mvebu_thermal_28nm.o
obj-$(CONFIG_MVEBU_THERMAL_EXT_SENSOR_28NM) += mvebu_ext_thermal_28nm.o
