#
# (C) Copyright 2014 Freescale Semiconductor, Inc.
# Author: Nitin Garg <nitin.garg@freescale.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_DM_THERMAL) += thermal-uclass.o
obj-$(CONFIG_IMX6_THERMAL) += imx_thermal.o
