#
# Copyright (C) 2007
# Yoshihiro Shimoda <shimoda.yoshihiro@renesas.com>
#
# Copyright (C) 2007
# Nobuhiro Iwamatsu <iwamatsu@nigauri.org>
#
# Copyright (C) 2007
# Kenati Technologies, Inc.
#
# (C) Copyright 2008
# Mark Jonas <mark.jonas@de.bosch.com>
#
# board/mpr2/Makefile
#
# SPDX-License-Identifier:	GPL-2.0+

obj-y	:= mpr2.o
extra-y	+= lowlevel_init.o
