#
# (C) Copyright 2002-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += cache_4xx.o
obj-y += cache.o
obj-y += denali_ecc.o
obj-y += ether.o
obj-y += fpu.o
obj-y += ocm.o
obj-y += spr.o
obj-y += uart.o
obj-y += watchdog.o
