#
# (C) Copyright 2002-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

CPPFLAGS += -I$(TOPDIR)

obj-$(CONFIG_HAS_POST)	+= cache_4xx.o
obj-$(CONFIG_HAS_POST)	+= cache.o
obj-$(CONFIG_HAS_POST)	+= denali_ecc.o
obj-$(CONFIG_HAS_POST)	+= ether.o
obj-$(CONFIG_HAS_POST)	+= fpu.o
obj-$(CONFIG_HAS_POST)	+= ocm.o
obj-$(CONFIG_HAS_POST)	+= spr.o
obj-$(CONFIG_HAS_POST)	+= uart.o
obj-$(CONFIG_HAS_POST)	+= watchdog.o
