# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2023 Svyatoslav Ryhel <clamor95@gmail.com>

obj-$(CONFIG_EXTCON) += extcon-uclass.o
obj-$(CONFIG_EXTCON_SANDBOX) += extcon-sandbox.o
obj-$(CONFIG_EXTCON_MAX14526) += extcon-max14526.o
