#
# Copyright (C) 2018 Grzegorz Jaszczyk <jaz@semihalf.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

ccflags-y += -Idrivers/ddr/marvell/a38x/ -Iarch/arm/mach-mvebu/serdes/a38x/
obj-y	:= db-88f6820-ap.o
