#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	= board.o cache.o interrupts.o time.o
obj-$(CONFIG_CMD_BOOTM) += bootm.o
