#
# Copyright (c) 2016 NextThing Co
# Copyright (c) 2016 Free Electrons
#
# SPDX-License-Identifier:	GPL-2.0+
#

# Test files
obj-y += cmd_ut_overlay.o

DTC_FLAGS += -@

# DT overlays
obj-y += test-fdt-base.dtb.o
obj-y += test-fdt-overlay.dtb.o
obj-y += test-fdt-overlay-stacked.dtb.o
