# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2015 Freescale Semiconductor, Inc.
#

obj-y	:= soc.o clock.o clock_slice.o ddr.o snvs.o

ifdef CONFIG_ARMV7_PSCI
obj-y  += psci-mx7.o psci.o
endif
