#
# (C) Copyright 2000-2003
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# Copyright (C) 2012 Altera Corporation <www.altera.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= lowlevel_init.o
obj-y	+= misc.o timer.o reset_manager.o system_manager.o
obj-$(CONFIG_SPL_BUILD) += spl.o freeze_controller.o
