#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2001
# Josh Huber <huber@mclx.com>, Mission Critical Linux, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	= misc.o
obj-y	+= cpci750.o serial.o ../../Marvell/common/memory.o pci.o \
	  mv_eth.o  mpsc.o i2c.o \
	  sdram_init.o ide.o
