#
# Makefile
#
# Copyright (C) 2012-2014, Birdland Audio - http://birdland.com/oem
#
# SPDX-License-Identifier:	GPL-2.0+
#

ifeq ($(CONFIG_SKIP_LOWLEVEL_INIT),)
obj-y	:= mux.o
endif

obj-y	+= board.o
