#
# board/renesas/v3hsk/Makefile
#
# Copyright (C) 2019 Renesas Electronics Corporation
# Copyright (C) 2019 Cogent Embedded, Inc.
#
# SPDX-License-Identifier: GPL-2.0+
#

ifndef CONFIG_XPL_BUILD
obj-$(CONFIG_SYSRESET)	+= cpld.o
endif
