#
# Copyright 2022 NXP
# Copyright (C) 2023 PHYTEC Messtechnik GmbH
# Christoph Stoidner <c.stoidner@phytec.de>
# Copyright (C) 2024 Mathieu Othacehe <m.othacehe@gmail.com>
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += phycore-imx93.o

ifdef CONFIG_SPL_BUILD
obj-y += spl.o lpddr4_timing.o
endif
