# SPDX-License-Identifier: GPL-2.0+
#
# Copyright 2014 Freescale Semiconductor, Inc.
# Copyright 2018 NXP

# Layerscape MC driver
obj-y += mc.o \
	mc_sys.o \
	dpmng.o	\
	dprc.o	\
	dpbp.o	\
	dpni.o	\
	dpmac.o	\
	dpsparser.o
obj-y += dpio/
