# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2025 MediaTek Inc.
# Author: Weijie Gao <weijie.gao@mediatek.com>

obj-y += mtk_eth.o
obj-$(CONFIG_MTK_ETH_SWITCH_MT7530) += mt753x.o mt7530.o
obj-$(CONFIG_MTK_ETH_SWITCH_MT7531) += mt753x.o mt7531.o
obj-$(CONFIG_MTK_ETH_SWITCH_MT7988) += mt753x.o mt7988.o
obj-$(CONFIG_MTK_ETH_SWITCH_AN8855) += an8855.o
