# SPDX-License-Identifier: GPL-2.0+

dtb-y += $(patsubst %,%.dtb,$(subst ",,$(CONFIG_DEFAULT_DEVICE_TREE) $(CONFIG_OF_LIST) $(CONFIG_SPL_OF_LIST)))

ifeq ($(CONFIG_OF_UPSTREAM_BUILD_VENDOR),y)
ifeq ($(CONFIG_ARM64),y)
dt_dir := $(srctree)/dts/upstream/src/arm64
else
dt_dir := $(srctree)/dts/upstream/src/$(ARCH)
endif

dtb-vendor_dts := $(patsubst %.dts,%.dtb,$(wildcard $(dt_dir)/$(subst ",,$(CONFIG_OF_UPSTREAM_VENDOR))/*.dts))

dtb-y += $(subst $(dt_dir)/,,$(dtb-vendor_dts))

endif
