# Makefile version of include/config_uncmd_spl.h
#
# SPDX-License-Identifier:	GPL-2.0+
#
# TODO: Invent a better way

ifdef CONFIG_SPL_BUILD

ifndef CONFIG_SPL_DM
CONFIG_DM_SERIAL=
CONFIG_DM_GPIO=
CONIFG_DM_I2C=
CONFIG_DM_SPI=
CONFIG_DM_SPI_FLASH=
endif

endif
