#
# (C) Copyright 2003-2008
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2010
# Reinhard Meyer, EMK Elektronik, reinhard.meyer@emk-elektronik.de
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= top9000.o
obj-$(CONFIG_ATMEL_SPI)	+= spi.o
