#
# (C) Copyright 2011 - 2013 CompuLab, Ltd. <www.compulab.co.il>
#
# Authors: Nikita Kiryanov <nikita@compulab.co.il>
#	   Igor Grinberg <grinberg@compulab.co.il>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_DRIVER_OMAP34XX_I2C) += eeprom.o
obj-$(CONFIG_LCD) += display.o

obj-y	+= cm_t35.o leds.o
