#
# (C) Copyright 2000, 2001, 2002
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2009
# Frederik Kriewitz <frederik@kriewitz.eu>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= devkit8000.o
