# SPDX-License-Identifier: GPL-2.0+
#
# Copyright 2022 DENX Software Engineering GmbH, Philip Oberfichtner <pro@denx.de>
#

obj-y += dh_common.o

ifneq (,$(CONFIG_ARCH_MX6)$(CONFIG_ARCH_IMX8M))
obj-y += dh_imx.o
endif
