# SPDX-License-Identifier:     GPL-2.0+
#
# https://beagleboard.org/play
#
# Copyright (C) 2022-2023 Texas Instruments Incorporated - https://www.ti.com/
# Copyright (C) 2022-2023 Robert Nelson, BeagleBoard.org Foundation
#

obj-y	+= beagleplay.o
