# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2021
# Francis Laniel, Amarula Solutions, francis.laniel@amarulasolutions.com

obj-y += if.o
ifdef CONFIG_CONSOLE_RECORD
obj-y += dollar.o
endif
obj-y += list.o
obj-y += loop.o
