#
# (C) Copyright 2002-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

CPPFLAGS += -I$(TOPDIR)

obj-$(CONFIG_HAS_POST) += asm.o
obj-$(CONFIG_HAS_POST) += cpu.o cmp.o cmpi.o two.o twox.o three.o threex.o
obj-$(CONFIG_HAS_POST) += threei.o andi.o srawi.o rlwnm.o rlwinm.o rlwimi.o
obj-$(CONFIG_HAS_POST) += store.o load.o cr.o b.o multi.o string.o complex.o

obj-$(CONFIG_HAS_POST) += fpu/
