# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2011 Nobuhiro Iwamatsu <iwamatsu@nigauri.org>
# Copyright (C) 2011 Nobuhiro Iwamatsu <nobuhiro.iwamatsu.yj@renesas.com>
#

obj-y := ecovec.o
extra-y += lowlevel_init.o
