#
# Copyright (C) 2011 Nobuhiro Iwamatsu <iwamatsu@nigauri.org>
# Copyright (C) 2011 Nobuhiro Iwamatsu <nobuhiro.iwamatsu.yj@renesas.com>
#
# SPDX-License-Identifier:	GPL-2.0+

obj-y := ecovec.o
obj-y += lowlevel_init.o
