# SPDX-License-Identifier: GPL-2.0-or-later
#
# (C) Copyright 2022 - Analog Devices, Inc.
#
# Written and/or maintained by Timesys Corporation
#
# Contact: Nathan Barrett-Morrison <nathan.morrison@timesys.com>
# Contact: Greg Malysa <greg.malysa@timesys.com>
#

obj-$(CONFIG_COMMON_CLK_ADI_SHARED) += clk-shared.o clk-adi-pll.o

obj-$(CONFIG_COMMON_CLK_ADI_SC594)  += clk-adi-sc594.o
obj-$(CONFIG_COMMON_CLK_ADI_SC598)  += clk-adi-sc598.o
obj-$(CONFIG_COMMON_CLK_ADI_SC58X)  += clk-adi-sc58x.o
obj-$(CONFIG_COMMON_CLK_ADI_SC57X)  += clk-adi-sc57x.o
