#
# board/renesas/eagle/Makefile
#
# Copyright (C) 2015 Renesas Electronics Corporation
#
# SPDX-License-Identifier: GPL-2.0+
#

ifdef CONFIG_XPL_BUILD
obj-y	:= ../common/gen3-spl.o
else
obj-y	:= ../common/v3-common.o ../common/gen3-common.o ../common/common.o
endif
