# SPDX-License-Identifier:      GPL-2.0+

obj-y += fb_common.o
obj-$(CONFIG_UDP_FUNCTION_FASTBOOT) += fb_getvar.o
obj-$(CONFIG_UDP_FUNCTION_FASTBOOT) += fb_command.o
obj-$(CONFIG_FASTBOOT_FLASH_MMC) += fb_mmc.o
obj-$(CONFIG_FASTBOOT_FLASH_NAND) += fb_nand.o
