#
# Copyright (C) 2007,2008 Nobuhiro Iwamatsu
# Copyright (C) 2008 Renesas Solutions Corp.
#
# u-boot/board/rsk7203/Makefile
#
# SPDX-License-Identifier:	GPL-2.0+

obj-y	:= rsk7203.o
obj-y	+= lowlevel_init.o
