# SPDX-License-Identifier: GPL-2.0+
# Copyright (C) 2015-2016 Texas Instruments Incorporated - https://www.ti.com/

obj-${CONFIG_TI_I2C_BOARD_DETECT} += board_detect.o
obj-${CONFIG_$(PHASE_)SUPPORT_EXTENSION_SCAN} += cape_detect.o
obj-${CONFIG_OF_LIBFDT} += fdt_ops.o
obj-${CONFIG_ARCH_K3} += k3-ddr.o
