#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2008
# Ricardo Ribalda-Universidad Autonoma de Madrid-ricardo.ribalda@uam.es
# Work supported by Qtechnology http://www.qtec.com
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= ../../xilinx/ppc440-generic/xilinx_ppc440_generic.o
extra-y 	+= ../../xilinx/ppc440-generic/init.o
