#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= ../common/common_util.o
obj-y	+= vcma9.o cmd_vcma9.o

obj-y	+= lowlevel_init.o
