# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2016 Nexell
# Junghyun, kim<jhkim@nexell.co.kr>

obj-$(CONFIG_VIDEO_NX) += s5pxx18_dp.o
obj-$(CONFIG_VIDEO_NX) += soc/

obj-$(CONFIG_VIDEO_NX_RGB)  += s5pxx18_dp_rgb.o
obj-$(CONFIG_VIDEO_NX_LVDS) += s5pxx18_dp_lvds.o
obj-$(CONFIG_VIDEO_NX_MIPI) += s5pxx18_dp_mipi.o
obj-$(CONFIG_VIDEO_NX_HDMI) += s5pxx18_dp_hdmi.o
