#ifndef _XPARAMETERS_H_
#define _XPARAMETERS_H_

#include "xparameters_pss.h"

#define STDIN_BASEADDRESS		XPAR_XUARTPSS_0_BASEADDR
#define STDOUT_BASEADDRESS		XPAR_XUARTPSS_0_BASEADDR

#define XPAR_DDR2_SDRAM_MEM_BASEADDR	0x00000000
#define XPAR_DDR2_SDRAM_MEM_HIGHADDR	0x00FFFFFF

/* SCU Timer */
#define XPAR_SCUTIMER_NUM_INSTANCES	1
#define XPAR_SCUTIMER_DEVICE_ID		0
#define XPAR_SCUTIMER_BASEADDR		0xFEF00600
#define XPAR_SCUTIMER_INTR		29

/* SCU Watchdog timer */
#define XPAR_SCUWDT_NUM_INSTANCES	1
#define XPAR_SCUWDT_DEVICE_ID		0
#define XPAR_SCUWDT_BASEADDR		0xFEF00600
#define XPAR_SCUWDT_INTR		30

/* SCU Interrupt Controller */
#define XPAR_SCUGIC_SINGLE_DEVICE_ID	0
#define XPAR_SCUGIC_CPU_BASEADDR	0xFEF00100
#define XPAR_SCUGIC_DIST_BASEADDR	0xFEF01000
#define XPAR_SCUGIC_NUM_INSTANCES	1
#define XPAR_SCUGIC_ACK_BEFORE		0

/* PSS Interrupt controller defines */
#define XPAR_GIC_SINGLE_DEVICE_ID	0
#define XPAR_GIC_CPU_BASEADDR		XPAR_SCUGIC_CPU_BASEADDR
#define XPAR_GIC_DIST_BASEADDR		XPAR_SCUGIC_DIST_BASEADDR
#define XPAR_GIC_NUM_INSTANCES		1
#define XPAR_GIC_ACK_BEFORE		0

/* UART Defines */
#define XPAR_XUARTPSS_NUM_INSTANCES	2
#define XPAR_XUARTPSS_0_DEVICE_ID	0
#define XPAR_XUARTPSS_0_BASEADDR	XPSS_UART0_BASEADDR
#define XPAR_XUARTPSS_0_CLOCK_HZ	50000000
#define XPAR_XUARTPSS_0_INTR		XPSS_UART0_INT_ID
#define XPAR_XUARTPSS_1_DEVICE_ID	1
#define XPAR_XUARTPSS_1_BASEADDR	XPSS_UART1_BASEADDR
#define XPAR_XUARTPSS_1_CLOCK_HZ	50000000
#define XPAR_XUARTPSS_1_INTR		XPSS_UART1_INT_ID

/*IIC Defines */
#define XPAR_XIICPSS_NUM_INSTANCES	2
#define XPAR_XIICPSS_0_DEVICE_ID	0
#define XPAR_XIICPSS_0_BASEADDR		XPSS_I2C0_BASEADDR
#define XPAR_XIICPSS_0_CLOCK_HZ		100000000
#define XPAR_XIICPSS_0_INTR		XPSS_I2C0_INT_ID
#define XPAR_XIICPSS_1_DEVICE_ID	1
#define XPAR_XIICPSS_1_BASEADDR		XPSS_I2C1_BASEADDR
#define XPAR_XIICPSS_1_CLOCK_HZ		100000000
#define XPAR_XIICPSS_1_INTR		XPSS_I2C1_INT_ID

/* SPI Defines */
#define XPAR_XSPIPSS_NUM_INSTANCES	2
#define XPAR_XSPIPSS_0_DEVICE_ID	0
#define XPAR_XSPIPSS_0_BASEADDR		XPSS_SPI0_BASEADDR
#define XPAR_XSPIPSS_0_CLOCK_HZ		50000000
#define XPAR_XSPIPSS_0_INTR		XPSS_SPI0_INT_ID
#define XPAR_XSPIPSS_1_DEVICE_ID	1
#define XPAR_XSPIPSS_1_BASEADDR		XPSS_SPI1_BASEADDR
#define XPAR_XSPIPSS_1_CLOCK_HZ		50000000
#define XPAR_XSPIPSS_1_INTR		XPSS_SPI1_INT_ID

/* CAN Defines */
#define XPAR_XCANPSS_NUM_INSTANCES	1
#define XPAR_XCANPSS_0_DEVICE_ID	0
#define XPAR_XCANPSS_0_BASEADDR		XPSS_CAN0_BASEADDR
#define XPAR_XCANPSS_0_INTR		XPSS_CAN0_INT_ID

/* DMA Defines */
#define XPAR_XDMAPSS_NUM_INSTANCES	1
#define XPAR_XDMAPSS_0_DEVICE_ID	0
#define XPAR_XDMAPSS_0_BASEADDR		XPSS_DMAC0_BASEADDR
#define XPAR_XDMAPSS_0_FAULT_INTR	XPSS_TOP_DMA_ABORT_INT_ID
#define XPAR_XDMAPSS_0_DONE_INTR_0	XPSS_TOP_DMA0_INT_ID
#define XPAR_XDMAPSS_0_DONE_INTR_1	XPSS_TOP_DMA1_INT_ID
#define XPAR_XDMAPSS_0_DONE_INTR_2	XPSS_TOP_DMA2_INT_ID
#define XPAR_XDMAPSS_0_DONE_INTR_3	XPSS_TOP_DMA3_INT_ID
#define XPAR_XDMAPSS_0_DONE_INTR_4	XPSS_BOT_DMA0_INT_ID
#define XPAR_XDMAPSS_0_DONE_INTR_5	XPSS_BOT_DMA1_INT_ID
#define XPAR_XDMAPSS_0_DONE_INTR_6	XPSS_BOT_DMA2_INT_ID
#define XPAR_XDMAPSS_0_DONE_INTR_7	XPSS_BOT_DMA3_INT_ID

#define XPAR_XDMAPSS_CHANNELS_PER_DEV	4

/* GPIO Defines*/
#define XPAR_XGPIO_NUM_INSTANCES	1
#define XPAR_XGPIO_0_DEVICE_ID		0
#define XPAR_XGPIO_0_BASEADDR		XPSS_GPIO_BASEADDR
#define XPAR_XGPIO_0_INTR		XPSS_GPIO_INT_ID

/* GEM Defines*/
#define XPAR_XEMACPSS_NUM_INSTANCES	1
#define XPAR_XEMACPSS_0_DEVICE_ID	0
#define XPAR_XEMACPSS_0_BASEADDR	XPSS_GEM0_BASEADDR
#define XPAR_XEMACPSS_0_INTR		XPSS_GEM0_INT_ID
#define XPAR_XEMACPSS_1_DEVICE_ID	1
#define XPAR_XEMACPSS_1_BASEADDR	XPSS_GEM1_BASEADDR

/* TTC Defines */
#define XPAR_XTTCPSS_NUM_INSTANCES	6
#define XPAR_XTTCPSS_CLOCK_HZ		781250

#define XPAR_XTTCPSS_0_DEVICE_ID	0
#define XPAR_XTTCPSS_0_BASEADDR		XPSS_TTC0_BASEADDR
#define XPAR_XTTCPSS_0_INTR		XPSS_TTC0_0_INT_ID
#define XPAR_XTTCPSS_0_CLOCK_HZ		XPAR_XTTCPSS_CLOCK_HZ

#define XPAR_XTTCPSS_1_DEVICE_ID	1
#define XPAR_XTTCPSS_1_BASEADDR		XPSS_TTC0_BASEADDR+4
#define XPAR_XTTCPSS_1_CLOCK_HZ		XPAR_XTTCPSS_CLOCK_HZ
#define XPAR_XTTCPSS_1_INTR		XPSS_TTC0_1_INT_ID

#define XPAR_XTTCPSS_2_DEVICE_ID	2
#define XPAR_XTTCPSS_2_BASEADDR		XPSS_TTC0_BASEADDR+8
#define XPAR_XTTCPSS_2_CLOCK_HZ		XPAR_XTTCPSS_CLOCK_HZ
#define XPAR_XTTCPSS_2_INTR		XPSS_TTC0_2_INT_ID

#define XPAR_XTTCPSS_3_DEVICE_ID	3
#define XPAR_XTTCPSS_3_BASEADDR		XPSS_TTC1_BASEADDR
#define XPAR_XTTCPSS_3_INTR		XPSS_TTC1_0_INT_ID
#define XPAR_XTTCPSS_3_CLOCK_HZ		XPAR_XTTCPSS_CLOCK_HZ

#define XPAR_XTTCPSS_4_DEVICE_ID	4
#define XPAR_XTTCPSS_4_BASEADDR		XPSS_TTC1_BASEADDR+4
#define XPAR_XTTCPSS_4_CLOCK_HZ		XPAR_XTTCPSS_CLOCK_HZ
#define XPAR_XTTCPSS_4_INTR		XPSS_TTC1_1_INT_ID

#define XPAR_XTTCPSS_5_DEVICE_ID	5
#define XPAR_XTTCPSS_5_BASEADDR		XPSS_TTC1_BASEADDR+8
#define XPAR_XTTCPSS_5_CLOCK_HZ		XPAR_XTTCPSS_CLOCK_HZ
#define XPAR_XTTCPSS_5_INTR		XPSS_TTC1_2_INT_ID

/* WDT Defines*/
#define XPSS_WDT_NUM_INSTANCES		1
#define XPSS_WDT_DEVICE_ID		0

/******************************************************************/
#define XPAR_CPU_CORTEXA9_CORE_CLOCK_FREQ_HZ	12500000
/******************************************************************/
#endif /*_XPARAMETERS_PSS_H_*/
