#
# (C) Copyright 2003-2008
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2009-2012
# Jens Scharsig  <esw@bus-elekronik.de>
# BuS Elektronik GmbH & Co. KG
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += vl_ma2sc.o
