#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

extra-y	= start.o
obj-y	= irq.o
obj-y	+= cpu.o interrupts.o cache.o exception.o timer.o
obj-$(CONFIG_SPL_BUILD)	+= spl.o
