#! /bin/sh
# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2023, Linaro Limited
#

gen_capsule_signature_file() {
cat >> $1 << EOF
/dts-v1/;
/plugin/;

&{/} {
	signature {
		capsule-key = /incbin/("$ESL_FILE");
	};
};
EOF
}

ESL_FILE="$1"
gen_capsule_signature_file signature.$$.dts > /dev/null 2>&1
dtc -@ -O dtb -o signature.$$.dtbo signature.$$.dts > /dev/null 2>&1
fdtoverlay -i $2 -o temp.$$.dtb -v signature.$$.dtbo > /dev/null 2>&1
mv temp.$$.dtb $2 > /dev/null 2>&1
rm -f signature.$$.* > /dev/null 2>&1
