#
# (C) Copyright 2003-2008
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2008
# Stelian Pop <stelian@popies.net>
# Lead Tech Design <www.leadtechdesign.com>
# Ilko Iliev <www.ronetix.at>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += pm9261.o
obj-$(CONFIG_RED_LED) += led.o
