# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2021, Steffen Jaeckel <jaeckel-floss@eyet-services.de>

obj-$(CONFIG_CRYPT_PW) += crypt.o
obj-$(CONFIG_CRYPT_PW_SHA256) += crypt-sha256.o
obj-$(CONFIG_CRYPT_PW_SHA512) += crypt-sha512.o
