#
# (C) Copyright 2002-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	= misc.o
obj-y	+= p3mx.o mpsc.o mv_eth.o pci.o sdram_init.o serial.o \
		../../Marvell/common/i2c.o ../../Marvell/common/memory.o
