#
# Copyright (C) 2013-2014 Synopsys, Inc. All rights reserved.
#
# SPDX-License-Identifier:	GPL-2.0+
#

# This board is mostly used for debugging U-Boot in simulation (ISS).
# The only peripheral which is used on this board is a serial port which
# requires no initialization except those in "include/configs/arcangel4.h".
# And now there's no specific initializations for this board.
# So this Makefile is only required for satisfaction of U-Boot build system.
