#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

# CFLAGS += -DET_DEBUG

extra-y	= start.o
obj-y	= interrupts.o cpu.o speed.o cpu_init.o
