#
# U-Boot - Makefile
#
# Copyright (c) 2005-2008 Analog Device Inc.
#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= bct-brettl2.o gpio_cfi_flash.o cled.o
obj-$(CONFIG_BFIN_MAC) += smsc9303.o
