#
# Copyright 2012 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= b4860qds.o
obj-y	+= ddr.o
obj-$(CONFIG_B4860QDS)+= eth_b4860qds.o
obj-$(CONFIG_PCI)	+= pci.o
obj-y	+= law.o
obj-y	+= tlb.o
