# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2015-2023 Tony Dinh <mibodhi@gmail.com>
#
# Based on
# (C) Copyright 2009
# Marvell Semiconductor <www.marvell.com>
# Written-by: Prafulla Wadaskar <prafulla@marvell.com>
#

obj-y	:= nsa325.o
