# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2025 Linaro Limited
#

obj-$(CONFIG_$(PHASE_)INTERCONNECT) += interconnect-uclass.o
obj-$(CONFIG_$(PHASE_)INTERCONNECT_SANDBOX) += sandbox-interconnect.o sandbox-interconnect-test.o
obj-y += qcom/
