#
# (C) Copyright 2008
# Ricardo Ribalda,Universidad Autonoma de Madrid, ricardo.ribalda@uam.es
# This work has been supported by: Qtechnology http://qtec.com/
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= ml507.o

include $(SRCTREE)/board/xilinx/ppc440-generic/Makefile
