#
# (C) Copyright 2019 Rockchip Electronics Co., Ltd
# Copyright (c) 2022 Edgeble AI Technologies Pvt. Ltd.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += rv1126.o

ifndef CONFIG_TPL_BUILD
obj-y += clk_rv1126.o
obj-y += syscon_rv1126.o
endif
