obj-y += ddr.o
obj-y += lpddr4_timing_ff020008.o
obj-y += lpddr4_timing_ff000110.o
ifdef CONFIG_TARGET_MCM_IMX8M_MINI
obj-y += lpddr4_timing_01061010.o
else
obj-y += lpddr4_timing_01061010.1_2.o
endif
