#
# SPDX-License-Identifier:      GPL-2.0+
#
# Copyright 2021 Hitachi Power Grids. All rights reserved.
#

obj-y += pg-wcom-ls102xa.o ddr.o
obj-y += ../common/common.o ../common/ivm.o ../common/qrio.o
obj-$(CONFIG_LAYERSCAPE_NS_ACCESS) += ../../freescale/common/ns_access.o
obj-$(CONFIG_LS102XA_STREAM_ID) += ../../freescale/common/ls102xa_stream_id.o
obj-$(CONFIG_ID_EEPROM) += ../../freescale/common/sys_eeprom.o
