#
# Makefile
#
# Copyright (C) 2015 Toby Churchill Ltd - http://www.toby-churchill.com/
#
# SPDX-License-Identifier:	GPL-2.0+
#

ifeq ($(CONFIG_SKIP_LOWLEVEL_INIT),)
obj-y	:= mux.o
endif

obj-y	+= board.o
