# SPDX-License-Identifier: GPL-2.0+
#
# Makefile
#
# Copyright (C) 2015 Toby Churchill Ltd - http://www.toby-churchill.com/

ifeq ($(CONFIG_$(SPL_)SKIP_LOWLEVEL_INIT),)
obj-y	:= mux.o
endif

obj-y	+= board.o
