#
# board/renesas/condor/Makefile
#
# Copyright (C) 2019 Renesas Electronics Corporation
#
# SPDX-License-Identifier: GPL-2.0+
#

ifdef CONFIG_XPL_BUILD
obj-y	:= ../common/gen3-spl.o
else
obj-y	:= ../common/gen3-common.o ../common/common.o
endif
