#
# (C) Copyright 2012-2014
#     Texas Instruments Incorporated, <www.ti.com>
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-y	+= aemif.o
obj-y	+= init.o
obj-y	+= psc.o
obj-y	+= clock.o
obj-y	+= cmd_clock.o
obj-y	+= cmd_mon.o
obj-y	+= keystone_nav.o
obj-y	+= msmc.o
obj-$(CONFIG_SPL_BUILD)	+= spl.o
obj-y	+= ddr3.o
