#
# (C) Copyright 2012-2014
#     Texas Instruments Incorporated, <www.ti.com>
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-y	+= init.o
obj-y	+= psc.o
obj-y	+= clock.o
obj-$(CONFIG_SOC_K2HK) += clock-k2hk.o
obj-$(CONFIG_SOC_K2E) += clock-k2e.o
obj-y	+= cmd_clock.o
obj-y	+= cmd_mon.o
obj-$(CONFIG_DRIVER_TI_KEYSTONE_NET) += keystone_nav.o
obj-y	+= msmc.o
obj-$(CONFIG_SPL_BUILD)	+= spl.o
obj-y	+= ddr3.o
obj-y	+= keystone.o
