#
# (C) Copyright 2013
# Avionic Design GmbH <www.avionic-design.de>
#
# SPDX-License-Identifier:	GPL-2.0+
#

$(shell mkdir -p $(obj)../common $(obj)../../nvidia/common)

obj-y	:= ../common/tamonten-ng.o

include ../../nvidia/common/common.mk
