#
# Copyright (C) 2009 Renesas Solutions Corp.
# Copyright (C) 2009 Nobuhiro Iwamatsu <iwamatsu.nobuhiro@renesas.com>
#
# board/espt/Makefile
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= espt.o
obj-y	+= lowlevel_init.o
