#
# U-Boot - Makefile
#
# Copyright (c) 2005-2007 Analog Device Inc.
#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= bf537-stamp.o
obj-$(CONFIG_BFIN_IDE)   += ide-cf.o
obj-$(CONFIG_HAS_POST)   += post-memory.o
