#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_ARCH_UNIPHIER_SLD3)	+= early-clk-ld4.o
obj-$(CONFIG_ARCH_UNIPHIER_LD4)		+= early-clk-ld4.o
obj-$(CONFIG_ARCH_UNIPHIER_PRO4)	+= early-clk-ld4.o
obj-$(CONFIG_ARCH_UNIPHIER_SLD8)	+= early-clk-ld4.o
obj-$(CONFIG_ARCH_UNIPHIER_PRO5)	+= early-clk-pro5.o
obj-$(CONFIG_ARCH_UNIPHIER_PXS2)	+= early-clk-pxs2.o
obj-$(CONFIG_ARCH_UNIPHIER_LD6B)	+= early-clk-pxs2.o
obj-$(CONFIG_ARCH_UNIPHIER_LD11)	+= early-clk-ld11.o
obj-$(CONFIG_ARCH_UNIPHIER_LD20)	+= early-clk-ld20.o
