obj-y					+= pinctrl-uclass.o
obj-$(CONFIG_$(SPL_)PINCTRL_GENERIC)	+= pinctrl-generic.o

obj-$(CONFIG_ARCH_ROCKCHIP) += rockchip/
obj-$(CONFIG_PINCTRL_SANDBOX)	+= pinctrl-sandbox.o

obj-$(CONFIG_ARCH_UNIPHIER)	+= uniphier/
