# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2024 Texas Instruments Incorporated - https://www.ti.com/
#	Andrew Davis <afd@ti.com>

obj-$(CONFIG_OF_SYSTEM_SETUP) += j784s4_fdt.o
obj-$(CONFIG_XPL_BUILD) += j784s4_init.o
