#
# (C) Copyright 2013
# Sergey Kostanbaev <sergey.kostanbaev <at> fairwaves.ru>
#
# (C) Copyright 2003-2006
# Wolfgang Denk, DENX Software Engineering, wd <at> denx.de.
#
# * SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= edb93xx.o
