#
# Copyright (C) 2020 Amarula Solutions(India)
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += icore_mx8mp.o

ifdef CONFIG_SPL_BUILD
obj-y += spl.o
obj-$(CONFIG_IMX8M_LPDDR4) += lpddr4_timing.o
endif
