# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2024 Texas Instruments Incorporated - https://www.ti.com/
#	Jayesh Choudhary <j-choudhary@ti.com>

obj-$(CONFIG_OF_SYSTEM_SETUP) += j722s_fdt.o
obj-$(CONFIG_XPL_BUILD) += j722s_init.o
